import { legacyStorageGuides } from './legacyStorageGuides.js';
import { legacyDataGuides } from './legacyDataGuides.js';
import { legacySystemsGuides } from './legacySystemsGuides.js';

const node = (label, detail) => ({ label, detail });
const term = (term, definition) => ({ term, definition });
const related = (id, reason) => ({ id, reason });
const exercise = (prompt, guidance) => ({ prompt, guidance });

// Editorial content only. paperGuides.js joins citations and frozen demo destinations by ID.
export const legacyGuideContent = {
  ...legacyStorageGuides,
  ...legacyDataGuides,
  ...legacySystemsGuides,
  chubby: {
    shortTitle: 'Chubby',
    problem: 'Loosely coupled services need a reliable way to agree on coarse-grained ownership and discover configuration. Making each application implement consensus couples application development to failure recovery.',
    ideas: ['Expose a small file-system-like namespace with advisory locks rather than a general transaction database.', 'Favor reliable low-volume coordination over high-throughput data movement; application participants must cooperate with the locking protocol.'],
    tradeoffs: ['An advisory lock cannot physically prevent an old client from accessing another service. The protected service must reject stale ownership evidence.', 'Session loss and process failure are different observations. A network interruption must not be treated as proof that the old owner stopped executing.'],
    prerequisites: ['Quorums and leader election', 'Leases and failure detection'],
    readingNotes: ['Start with the interface and intended uses. Contrast coarse-grained locks with fine-grained database locks.', 'Read the discussion of actual usage and design changes before concluding that the originally anticipated workload was correct.'],
    diagram: [node('Acquire', 'A client obtains ownership through the coordination service.'), node('Use', 'The application sends ownership evidence with protected work.'), node('Validate', 'The resource checks freshness instead of trusting client liveness.')],
    glossary: [term('Advisory lock', 'A lock whose correctness depends on participants respecting it.'), term('Sequencer', 'Evidence of a lock generation that a recipient can use to detect stale holders.')],
    exercise: exercise('Client A pauses while holding a lock; B later acquires it. A resumes and sends a delayed write. Where must stale-owner rejection happen?', 'At the protected resource, not merely in B or in the lock client. Draw the delayed write crossing the ownership change and explain why two successful lock acquisitions at different times do not imply simultaneous safe access.'),
    related: [related('zookeeper', 'Compare a coordination API and client-side recipes with a lock-oriented service.'), related('paxos-simple', 'Separate the agreement mechanism from the service interface built above it.')],
  },
  borg: {
    shortTitle: 'Borg',
    problem: 'A large shared cluster must keep machines busy while allowing important services to survive failures and contention. Reserving every workload for its worst case wastes capacity.',
    ideas: ['Combine admission control, task packing, overcommitment, and process-level isolation instead of relying on one placement heuristic.', 'Use scheduling policies and fast recovery to reduce correlated failures; expose declarative jobs and monitoring so users can operate the result.'],
    tradeoffs: ['Overcommitment depends on spare capacity actually existing when important workloads need it. Simultaneous bursts can invalidate average-use estimates.', 'Tight packing and failure isolation pull in different directions: packing every replica onto one machine is efficient only until that machine fails.'],
    prerequisites: ['CPU and memory resource accounting', 'Failure domains'],
    readingNotes: ['Map admission, placement, and runtime recovery into separate decisions.', 'Inspect the policy evaluation and workload mix before borrowing utilization results for a different cluster.'],
    diagram: [node('Declare', 'Jobs specify resources, constraints, and importance.'), node('Place', 'Admission and task packing select feasible machines.'), node('Recover', 'Runtime monitoring detects loss and restores desired work.')],
    glossary: [term('Overcommitment', 'Allocating based on expected usage rather than the sum of worst-case reservations.'), term('Correlated failure', 'One event disables several components that were expected to provide redundancy.')],
    exercise: exercise('Three replicas fit on one host. Spread them over three hosts instead. What capacity and failure assumptions must you add?', 'Account for host-level headroom and the spare resources required to reschedule a lost replica. Spreading prevents one host failure from losing every replica but does not protect against their shared rack or power failure.'),
    related: [related('autopilot', 'Compare choosing resource sizes with placing workloads of those sizes.'), related('sre-capacity-management', 'Relate immediate scheduling to longer-term capacity intent.')],
  },
  dremel: {
    shortTitle: 'Dremel',
    problem: 'Ad hoc aggregates over huge nested datasets need much lower latency than a general batch job can offer. Reading every field of every record wastes I/O when a query uses only a few fields.',
    ideas: ['Represent nested data in columns so queries can read selected fields without reconstructing every whole record.', 'Combine multilevel execution trees with parallel scans and aggregation; Dremel complements rather than replaces MapReduce.'],
    tradeoffs: ['The cited design analyzes read-only nested data. Do not infer an OLTP update or transaction protocol from the query engine.', 'Column pruning saves I/O only when the query needs a subset of fields. Serving-tree fan-out also introduces stragglers and coordination costs.'],
    prerequisites: ['Columnar versus row-oriented layout', 'Associative aggregation'],
    readingNotes: ['Study the nested representation before the serving tree; repetition structure must survive column separation.', 'The linked citation is the CACM edition. Treat its reported scale as an evaluated workload, not a latency guarantee for every query.'],
    diagram: [node('Project', 'Choose only the nested fields needed by the query.'), node('Scan', 'Leaf work reads column data in parallel.'), node('Aggregate', 'Intermediate results move up a multilevel serving tree.')],
    glossary: [term('Projection', 'Selecting a subset of fields or columns.'), term('Serving tree', 'A hierarchy that distributes query work and combines partial results.')],
    exercise: exercise('A query computes AVG(x) over shards with 2 and 8 rows. Can a parent average the two shard averages?', 'No, not unless counts match. Return sum and count from each child, add the sums and counts, and divide once. This is an illustrative aggregate-design exercise, not a Dremel benchmark.'),
    related: [related('mapreduce', 'Compare interactive aggregation with general batch transformations.'), related('napa', 'Follow the later warehouse emphasis on robust query performance.')],
  },
  megastore: {
    shortTitle: 'Megastore',
    problem: 'Interactive services need wide-area replication and structured transactional data without putting the entire database behind one serial transaction stream.',
    ideas: ['Partition data into entity groups with serializable ACID semantics inside each group.', 'Synchronously replicate writes across the wide area while allowing independent groups to progress separately.'],
    tradeoffs: ['Entity-group choice defines a transaction boundary and a contention boundary. A giant group loses much of the available parallelism.', 'Wide-area synchronous replication introduces latency and quorum availability constraints; high availability is not a promise to write through every partition.'],
    prerequisites: ['Serializability', 'Replication logs and quorums'],
    readingNotes: ['Identify the scope of the ACID guarantee before considering replication optimizations.', 'Use the replication discussion to distinguish durable agreement from the application schema that chooses entity groups.'],
    diagram: [node('Group', 'Place related records inside a transaction domain.'), node('Order', 'Agree on the group update through replication.'), node('Serve', 'Expose a consistent result while other groups progress independently.')],
    glossary: [term('Entity group', 'A fine-grained partition that bounds the strong transactional guarantee.'), term('Synchronous replication', 'The write completion path waits for required remote replication work.')],
    exercise: exercise('Would you group all customers together or each customer and their orders? Explain a transfer between customers.', 'Per-customer groups permit independent progress but make a cross-customer transfer cross a boundary. A larger group eases that transaction while increasing contention. Do not assume a single-group guarantee automatically extends across groups.'),
    related: [related('spanner', 'Compare transaction boundaries with a globally distributed database.'), related('dynamo', 'Contrast synchronous agreement with availability-oriented conflict resolution.')],
  },
  percolator: {
    shortTitle: 'Percolator',
    problem: 'A web index receives small independent updates continuously. Rebuilding large batches delays freshness, while traditional databases did not fit the storage and throughput requirements described by the authors.',
    ideas: ['Use distributed transactions to apply related incremental mutations rather than periodically recomputing the entire repository.', 'Use notifications to trigger dependent processing when underlying data changes, connecting storage mutation to incremental computation.'],
    tradeoffs: ['Incremental work adds transactional and notification overhead. It is most attractive when updates touch a small portion of the repository.', 'Snapshot isolation is not a blanket serializability guarantee. Application invariants spanning independently written rows still need careful design.'],
    prerequisites: ['Multi-version storage', 'Two-phase commit and write conflicts'],
    readingNotes: ['Read the motivation as a workload argument: large data plus small mutations, not a claim that batch processing is obsolete.', 'Trace the primary commit point and recovery separately in the paper, then use the existing two-row model to inspect crash timing.'],
    diagram: [node('Mutate', 'A crawled document changes a small part of the stored index.'), node('Commit', 'Related writes become a transactionally visible update.'), node('Notify', 'Dependent work reacts without rebuilding all unrelated data.')],
    glossary: [term('Incremental processing', 'Recomputing effects of changes rather than the whole dataset.'), term('Snapshot isolation', 'Reads see a consistent snapshot and conflicting concurrent writes are constrained, but write skew may remain.')],
    exercise: exercise('An index contains 1,000 pages; 10 change. Compare a full scan with one update per changed page. What is missing from a simple 100x speedup claim?', 'Dependency fan-out, transaction coordination, read/write amplification, and notification work. Ten changed pages can invalidate many derived records. The count ratio alone is not a runtime ratio.'),
    related: [related('mapreduce', 'Compare freshness and coordination costs with a batch pipeline.'), related('bigtable', 'Separate the storage substrate from cross-row transactional behavior.')],
  },
  millwheel: {
    shortTitle: 'MillWheel',
    problem: 'A continuous anomaly detector must preserve state and logical-time meaning despite out-of-order records and worker failures. An always-running process alone does not provide a fault-tolerant stream computation.',
    ideas: ['Express a directed graph of computations with managed persistent state and continuous record flow.', 'Use logical time to support time-based aggregation, while fault tolerance protects state transitions and processing across recovery.'],
    tradeoffs: ['Progress depends on upstream time information, not simply on the fastest arriving record. A slow input can delay a safe time-based decision.', 'Exactly-once state transitions inside the framework do not automatically make an arbitrary external side effect exactly once.'],
    prerequisites: ['Event time versus processing time', 'Checkpointing and duplicate delivery'],
    readingNotes: ['Follow the anomaly-detector case study to see why timers and logical time are needed.', 'Read the fault-tolerance mechanism alongside the programming model; distinguish record delivery from durable effects.'],
    diagram: [node('Receive', 'Records carry keys and logical timestamps.'), node('Persist', 'Computation updates managed state under the fault-tolerance contract.'), node('Advance', 'Time progress allows timers and aggregates to become actionable.')],
    glossary: [term('Logical time', 'The time attached to a computation record, distinct from wall-clock arrival.'), term('Low watermark', 'A progress bound used to reason about outstanding earlier work.')],
    exercise: exercise('Two inputs report progress at 90 and 40. Is a window ending at 60 complete merely because one input reached 90?', 'No. The slower relevant input still permits earlier work. Determine whether its progress is a strict bound or an estimate, and specify a late-data policy rather than treating wall-clock waiting as proof.'),
    related: [related('dataflow', 'Compare the later explicit window, trigger, and accumulation choices.'), related('photon-pubsub', 'Contrast general streaming state with a continuous join use case.')],
  },
  colossus: {
    shortTitle: 'Colossus architecture',
    problem: 'A cluster-level file system needs to scale metadata and data independently while serving many workloads with different latency, cost, and durability requirements.',
    ideas: ['Curators provide a scalable metadata control plane backed by Bigtable; clients transfer data directly to D file servers.', 'Custodians perform background balancing and reconstruction. Client libraries select encodings appropriate to workload requirements.'],
    tradeoffs: ['This is an official engineering overview, not a complete protocol specification or peer-reviewed performance evaluation.', 'Repair consumes I/O and network capacity. A fragment-count exercise cannot model placement correlation, repair scheduling, or real durability probabilities.'],
    prerequisites: ['Control plane versus data plane', 'Replication and erasure coding'],
    readingNotes: ['Inspect the control-plane diagram and identify which operations contact curators versus D servers.', 'Read storage efficiency as a workload-mixing argument. Distinguish the article statements from the simplified local erasure-code lab.'],
    diagram: [node('Locate', 'Client talks to a curator for metadata operations.'), node('Transfer', 'Client communicates directly with D file servers.'), node('Maintain', 'Custodians rebalance data and reconstruct lost redundancy.')],
    glossary: [term('Curator', 'A Colossus metadata service component.'), term('Custodian', 'A background manager responsible for storage maintenance such as balancing and reconstruction.')],
    exercise: exercise('If a client can find a file but cannot read its bytes, which paths would you inspect separately?', 'Metadata availability does not establish data-path availability. Trace curator and metadata access separately from D-server reachability, coding requirements, and repair capacity. The article does not specify every failure-state transition.'),
    related: [related('gfs', 'Compare the predecessor and its metadata scalability constraints.'), related('bigtable', 'Identify the metadata database beneath the curators.')],
  },
  druid: {
    shortTitle: 'Druid architecture',
    problem: 'Analytical ingestion, query routing, durable segment storage, and low-latency serving have different scaling needs. Putting them in one inseparable process makes independent growth and recovery harder.',
    ideas: ['Separate Coordinator and Overlord management from Broker query fan-out and Historical segment serving.', 'Persist segments in deep storage; Historicals load queryable copies while ingestion tasks publish new segments.'],
    tradeoffs: ['The latest documentation is a moving target, not an immutable paper edition. Service roles and deployment choices should be checked against the deployed version.', 'Querying data only in deep storage trades latency for a larger accessible dataset. Local Historical copies improve serving performance but consume capacity.'],
    prerequisites: ['Immutable segments', 'Object storage versus local disk'],
    readingNotes: ['Walk the documented service diagram twice, once for ingestion and once for queries.', 'Read external dependencies: deep storage, metadata storage, and ZooKeeper serve distinct purposes and cannot be treated as interchangeable backups.'],
    diagram: [node('Ingest', 'Overlord assigns work; tasks publish segments.'), node('Place', 'Coordinator manages availability on Historical services.'), node('Query', 'Broker fans out and merges partial query results.')],
    glossary: [term('Historical', 'A service that loads and queries immutable segments without accepting writes to them.'), term('Deep storage', 'Shared durable storage for ingested segments and a recovery source for serving nodes.')],
    exercise: exercise('All Historical nodes are replaced but deep storage survives. Is immediate full query performance guaranteed?', 'No. Durable segments allow recovery, but loading data, restoring metadata-dependent coordination, and warming serving capacity take time. Distinguish recoverability from uninterrupted low latency.'),
    related: [related('dremel', 'Compare query fan-out and aggregation designs.'), related('kafka', 'Contrast a stream log with the analytical serving system consuming it.')],
  },
  'sre-capacity-management': {
    shortTitle: 'Intent-based capacity planning',
    problem: 'A spreadsheet that requests fixed cores in fixed clusters becomes brittle when demand, supply dates, or dependency latency changes. The reasons behind each placement request are easily lost.',
    ideas: ['Encode service intent, dependencies, performance conversions, supply, prices, and priorities as inputs to a capacity plan.', 'Auxon separates configuration, solving, and allocation output so the solver can evolve without forcing every customer to replace their tools.'],
    tradeoffs: ['An optimizer only solves the modeled constraints. Incorrect demand or performance data can produce a precise but unsafe plan.', 'Priorities make resource shortfalls explicit; no algorithm can satisfy requirements that exceed feasible supply.'],
    prerequisites: ['Demand forecasts', 'Resource bottlenecks and failure domains'],
    readingNotes: ['Follow the chapter example from fixed cores to geographic redundancy intent.', 'Read the Stupid Solver and modularity discussion before assuming optimal mathematical solving must precede useful deployment.'],
    diagram: [node('Describe intent', 'Express redundancy, latency, and demand constraints.'), node('Solve', 'Combine performance data, supply, pricing, and priorities.'), node('Allocate', 'Produce placements and expose unmet requirements.')],
    glossary: [term('Intent', 'The requirement motivating an allocation, not merely a chosen placement.'), term('Performance conversion', 'A relationship that translates service demand into dependency resource demand.')],
    exercise: exercise('A frontend needs a database within 30 ms. Why can unused cores in a distant region fail to solve its capacity shortage?', 'Capacity has constraints beyond quantity. The database placement and latency dependency may make those cores infeasible. Capture the dependency explicitly rather than changing a single global core total.'),
    related: [related('borg', 'Distinguish planning future supply from scheduling current tasks.'), related('sre-workbook', 'Use reliability goals to justify capacity requirements.')],
  },
  'sre-workbook': {
    shortTitle: 'Implementing SLOs',
    problem: 'A reliability percentage is not a useful engineering policy unless it measures user outcomes and stakeholders agree what to do when the service falls below target.',
    ideas: ['Define an SLI specification before choosing an implementation such as server logs, probes, or client instrumentation.', 'Use error budgets to prioritize reliability work and create a written policy with owners, actions, and an escalation path.'],
    tradeoffs: ['Server logs miss failures that never reach the server. Measurement location changes coverage and the meaning of the denominator.', 'A 100% target leaves no error budget. A more permissive target still needs stakeholder agreement and ongoing validation against user experience.'],
    prerequisites: ['Ratios and rolling windows', 'User journeys and failure signals'],
    readingNotes: ['Read the distinction between SLI specification and implementation before copying a dashboard metric.', 'Follow the worked example through stakeholder agreement and policy enforcement, not only the percentage calculation.'],
    diagram: [node('Specify', 'Choose the user outcome and eligible event population.'), node('Measure', 'Count good and total events with known coverage gaps.'), node('Act', 'Apply the agreed error-budget policy and refine the SLO.')],
    glossary: [term('SLI specification', 'The user outcome to assess, independent of its instrumentation.'), term('Error budget', 'The allowed unsuccessful fraction implied by the reliability target over its defined window.')],
    exercise: exercise('At 99.9% success over 3 million requests, how much of the budget does a 1,500-error outage consume?', 'The allowed errors are 3,000, so the outage consumes 50%. This is the chapter example. If failures never reach your measured endpoint, the arithmetic can be correct while the SLI still understates user pain.'),
    related: [related('monarch', 'Connect reliability decisions to a monitoring storage system.'), related('tail-at-scale', 'Explain why a good average can hide an unacceptable user tail.')],
  },
  'virtual-memory': {
    shortTitle: 'Virtual memory reading desk',
    problem: 'Applications need isolated address spaces larger and simpler than the physical memory layout. Translation must be efficient, and missing physical pages need a separate recovery mechanism.',
    ideas: ['Split a virtual address into a page number and offset; page tables map virtual pages to physical frames.', 'A TLB caches translations. A TLB miss can be resolved without disk I/O when the page is already resident.'],
    tradeoffs: ['Page tables consume memory; smaller pages reduce internal fragmentation but increase translation metadata.', 'Working sets larger than available frames can cause repeated page faults. A larger address space does not create more physical RAM.'],
    prerequisites: ['Binary addresses', 'Caches and locality'],
    readingNotes: ['Use OSTEP chapters 18-20 for paging, TLBs, and page-table size.', 'Then read chapters 21-22 for swapping mechanisms and policies. Keep replacement policy separate from address translation.'],
    diagram: [node('Translate', 'Look up the virtual page in a TLB or page table.'), node('Check', 'Validate permissions and residency before using the frame.'), node('Recover', 'A nonresident page requires fault handling before retry.')],
    glossary: [term('TLB miss', 'The translation cache lacks an entry; the data page may still be resident.'), term('Page fault', 'An access traps because its page or permission state requires OS handling.')],
    exercise: exercise('With 4 KiB pages, split address 0x3123 into page number and offset. If frame 9 holds the page, what address results?', 'The virtual page is 3 and the offset is 0x123. Frame 9 gives physical address 0x9123. A missing TLB entry alone does not imply the page must be read from disk.'),
    related: [related('gorilla', 'Connect memory footprint to how much recent monitoring data stays resident.'), related('thread-per-core-tail-latency', 'Compare address-space mechanisms with CPU-local execution choices.')],
  },
  'bloom-paradox': {
    shortTitle: 'Bloom filters: when filtering costs more',
    problem: 'An exact lookup may be expensive enough to justify a compact approximate membership test. But the filter consumes memory and CPU, and positives still need an exact lookup.',
    ideas: ['Insert each key by setting hashed bit positions. A missing bit proves absence; all bits set indicate only possible membership.', 'Evaluate the filter as part of a lookup cost model, not only by its false-positive rate. Most-positive workloads can pay filter overhead with little avoided I/O.'],
    tradeoffs: ['No-false-negative behavior assumes no bit clearing and consistent hashing. Deleting by clearing shared bits violates that assumption.', 'The familiar probability approximation assumes suitably independent uniform hashes. The deterministic toy hash experiment shows actual counts, not proof of those assumptions.'],
    prerequisites: ['Hashing', 'Conditional probability and expected cost'],
    readingNotes: ['Use the 1970 reference for the space/time/error tradeoff; Bloom Paradox is an editorial title.', 'In the experiment, distinguish false positives among absent keys from the fraction of all queries requiring exact lookup.'],
    diagram: [node('Insert', 'Set each key hash position without clearing existing bits.'), node('Probe', 'A zero bit rules out membership; otherwise consult the exact store.'), node('Account', 'Charge every filter probe and only the exact lookups that remain.')],
    glossary: [term('False positive', 'An absent key whose hash positions are all set.'), term('Break-even', 'The saved exact-lookup cost equals the added filter cost.')],
    exercise: exercise('If 90% of queries hit, absent-key false positives are 1%, and every filter probe costs 0.2 exact lookups, is filtering beneficial?', 'Expected cost is 0.2 + 0.9 + 0.1 × 0.01 = 1.101, compared with 1 without a filter. A low false-positive rate is insufficient when there are few negative lookups to eliminate.'),
    related: [related('bigtable', 'Consider reducing unnecessary immutable-table reads.'), related('myrocks1', 'Place filtering inside the wider read/write/space amplification tradeoff.')],
  },
  gorilla: {
    shortTitle: 'Gorilla compression',
    problem: 'Recent monitoring measurements are especially valuable during incidents, but retaining them in RAM needs a much smaller representation than raw timestamp/value pairs.',
    ideas: ['Encode changes in timestamp deltas; regular sampling makes most delta-of-delta values zero.', 'XOR adjacent floating-point bit patterns. Repeated values need little information, while similar patterns can share leading and trailing zero regions.'],
    tradeoffs: ['Monitoring emphasizes recent aggregates; the paper accepts possible small write-path data loss to preserve availability. This is not a ledger durability contract.', 'Compression depends on the actual timestamp and value sequence. Irregular timing or changing bit patterns can cost more than regular samples.'],
    prerequisites: ['IEEE-754 floating-point representation', 'Lossless compression and XOR'],
    readingNotes: ['Read the timestamp and value compression algorithms separately, including their control bits and stored window metadata.', 'Compare the availability goal with a financial database before generalizing the evaluation. The local timestamp experiment omits block headers and value compression.'],
    diagram: [node('Predict time', 'Use the prior interval to predict the next timestamp.'), node('Encode residual', 'Choose a control prefix and signed delta-of-delta payload.'), node('Recover', 'Add the decoded residual to the prior delta, then to time.')],
    glossary: [term('Delta-of-delta', 'The difference between consecutive timestamp intervals.'), term('XOR residual', 'The bitwise difference between successive encoded values; zero means identical bits.')],
    exercise: exercise('For timestamps 100, 110, 120, 131, 141, list the intervals and residuals after the first interval.', 'Intervals are 10, 10, 11, 10. Delta-of-delta residuals are 0, 1, -1. Reconstruct each timestamp in order; the residual is not the absolute interval.'),
    related: [related('monarch', 'Compare another large-scale in-memory monitoring system.'), related('virtual-memory', 'Relate compression savings to the working set that can remain in RAM.')],
  },
  'google-infrastructure-security': {
    shortTitle: 'Infrastructure security layers',
    problem: 'Shared infrastructure hosts many services and customer workloads. Network location alone cannot establish whether a caller, binary, or machine should be trusted with data.',
    ideas: ['Bind service and machine identities to authenticated communication and enforce per-service authorization.', 'Apply progressive protections to boot integrity, deployment, stored data, internet entry, and operator access rather than relying on one perimeter.'],
    tradeoffs: ['This document states the June 2024 design context and is not a complete implementation specification or a guarantee that every product has identical controls.', 'Authentication proves an identity, not permission for every operation. Encryption protects data paths but does not fix overbroad authorization.'],
    prerequisites: ['Authentication versus authorization', 'Encryption in transit and at rest'],
    readingNotes: ['Trace an inter-service RPC and list identity, authorization, and transport checks separately.', 'Read the operator and source-code protections as part of the system threat model, not as unrelated administrative notes.'],
    diagram: [node('Establish identity', 'Machine and service credentials identify participants.'), node('Authorize', 'A policy limits methods and data the caller may access.'), node('Audit and protect', 'Transport, storage, deployment, and operational controls provide additional layers.')],
    glossary: [term('Service identity', 'A cryptographic identity associated with a running service.'), term('Root of trust', 'A foundational component relied upon to validate other system components.')],
    exercise: exercise('A caller has a valid service certificate but is absent from the target allowlist. Should encrypted transport make the request succeed?', 'No. Valid credentials and confidentiality do not grant authorization. The target must enforce the service access policy. Use the existing layered-check model to separate these decisions.'),
    related: [related('zanzibar', 'Compare infrastructure identity with application relationship-based authorization.'), related('borg', 'Relate service deployment to the cluster orchestration layer.')],
  },
};
