const node = (label, detail) => ({ label, detail });
const term = (term, definition) => ({ term, definition });
const related = (id, reason) => ({ id, reason });
const exercise = (prompt, guidance) => ({ prompt, guidance });

export const legacySystemsGuides = {
  mendel: {
    shortTitle: 'Mendel experiments',
    problem: 'A product team wants many simultaneous experiments, but dividing users into one global set of mutually exclusive tests severely limits experimental capacity.',
    ideas: ['Organize experiments into layers so a user can participate in different independent parameter changes at once.', 'Combine assignment infrastructure with analysis tools, launch controls, and education. Correct randomization alone does not ensure a trustworthy decision.'],
    tradeoffs: ['Independent assignment does not prove treatment effects are independent. Interactions across layers can change the meaning of a measured average effect.', 'Two experiments that modify the same parameter need explicit exclusion or coordination. Overlap is useful only with a clear ownership model.'],
    prerequisites: ['Randomized controlled experiments', 'Interaction effects and experimental units'],
    readingNotes: ['Read the layer model and parameter separation first. Draw user assignment separately from which settings change.', 'Then read the tooling and process discussion, including how teams learn to interpret results. Throughput of experiments is not itself evidence of better decisions.'],
    diagram: [node('Assign by layer', 'A stable experimental unit receives an assignment within each layer.'), node('Apply parameters', 'Treatments modify the parameter sets owned by their experiments.'), node('Analyze outcomes', 'Check effects, interactions, and experiment validity before a launch decision.')],
    glossary: [term('Layer', 'An assignment space used to organize experiments over a parameter set.'), term('Interaction effect', 'A treatment effect that changes depending on another simultaneous treatment.')],
    exercise: exercise('Two independent 10% experiments run in different layers. What fraction of users is expected in both, and does that prove no interaction?', 'Under independent assignment, 0.1 × 0.1 = 1% is expected in both. That arithmetic says nothing about whether their product effects interact. Compare outcomes by joint assignment if the interaction is plausible.'),
    related: [related('sre-workbook', 'Pair launch decisions with service reliability guardrails.'), related('google-search-anatomy', 'Distinguish the ranking mechanism from experiments used to evaluate changes to it.')],
  },
  'anycast-load-balancing': {
    shortTitle: 'Anycast operations guide',
    problem: 'A network service needs multiple serving locations behind one destination address, with routing able to move traffic when a location becomes unavailable.',
    ideas: ['Advertise the same service address from several nodes and let routing policy determine each node catchment.', 'Tie route advertisement to service health and plan for routing convergence, monitoring, and operational recovery.'],
    tradeoffs: ['Routing preference is not a guarantee of nearest physical distance, lowest measured latency, or even load distribution.', 'A route change can move packets from an established session to a node without its state. Stateful protocols require additional continuity design.'],
    prerequisites: ['IP routing and BGP', 'Stateless versus stateful requests'],
    readingNotes: ['RFC 4786 is an operational best-practice document. Start with terminology and the distinction between local and global nodes.', 'Read service considerations and failure behavior before interpreting anycast as an application-level load balancer.'],
    diagram: [node('Advertise service', 'Several locations announce reachability for one address.'), node('Select route', 'Network policy determines which node receives client packets.'), node('Withdraw on failure', 'Health and routing changes shift the catchment after convergence.')],
    glossary: [term('Catchment', 'The set of clients whose routing currently leads to one anycast node.'), term('Route withdrawal', 'Removal of an advertised route so other paths may be selected.')],
    exercise: exercise('A server process fails but its router keeps advertising the service address. Will anycast automatically avoid that site?', 'Not necessarily. Routing can remain healthy while the application is dead. Couple appropriate health signals to announcements and account for convergence delay and false-positive health failures.'),
    related: [related('quic', 'Compare network-path changes with transport connection identity and migration.'), related('jupiter-rising', 'Contrast Internet route policy with a planned datacenter fabric.')],
  },
  bitcoin: {
    shortTitle: 'Bitcoin white paper',
    problem: 'A peer-to-peer cash network must agree on transaction history and resist double spending without a central party assigning a total order.',
    ideas: ['Link blocks with hashes and require proof of work so rewriting history entails computational work.', 'Follow the valid chain with the greatest accumulated proof of work; additional confirmations reduce reversal risk under the paper assumptions.'],
    tradeoffs: ['Safety is probabilistic and depends on the honest-computing-power and network assumptions. A chosen confirmation count is not deterministic finality.', 'Proof of work costs resources and constrains settlement latency. Signatures prove authorization to spend, not that conflicting spends cannot exist.'],
    prerequisites: ['Cryptographic hashes and signatures', 'Probability and adversarial behavior'],
    readingNotes: ['Separate the digital-signature chain from the proof-of-work chain in the transaction and timestamp-server sections.', 'Read the attacker calculation with its assumptions. This workspace discusses the 2008 design rather than certifying a current implementation or financial use.'],
    diagram: [node('Broadcast transaction', 'Nodes receive a signed candidate spend.'), node('Extend work chain', 'Miners construct valid blocks and perform proof of work.'), node('Observe confirmations', 'Further accumulated work increases confidence in the history.')],
    glossary: [term('Double spending', 'Attempting to spend the same available value in conflicting transactions.'), term('Confirmation depth', 'The number of blocks establishing and extending a transaction inclusion.')],
    exercise: exercise('Two valid blocks are found at almost the same time. Have signatures failed, and what resolves the temporary fork?', 'No. Both can contain valid authorized transactions. Nodes may temporarily see different tips; subsequent accumulated work selects a branch. Transactions on the abandoned branch require reconsideration under the winning history.'),
    related: [related('paxos-simple', 'Contrast open proof-of-work participation with fixed-member quorum agreement.'), related('dynamo', 'Compare temporary divergent histories with application-level version reconciliation.')],
  },
  'paxos-made-live': {
    shortTitle: 'Paxos Made Live',
    problem: 'A proven consensus algorithm is not yet a production replicated database. Storage corruption, recovery, testing, and operational mistakes exist outside a short protocol proof.',
    ideas: ['Build a replicated log and state machine around Paxos, while preserving the protocol assumptions through persistence and recovery.', 'Treat engineering validation, fault handling, and operational controls as part of correctness rather than as packaging after the algorithm.'],
    tradeoffs: ['Crash-recovery reasoning assumes trustworthy persisted state. A corrupt disk or implementation bug can violate an acceptor promise in ways an ordinary timeout cannot.', 'Optimizations and operational procedures can alter protocol behavior. Testing one successful leader election is insufficient evidence for safe long-running recovery.'],
    prerequisites: ['Paxos Made Simple', 'Persistent logs and state-machine replication'],
    readingNotes: ['Read the algorithmic challenges and engineering challenges as separate lists, then connect each mitigation to a stated assumption.', 'Focus on disk corruption, testing, and unexpected failures. The citation is the 2007 proceedings work even though the landing title mentions a 2006 talk.'],
    diagram: [node('Agree on log', 'Replicas select an ordered sequence of commands.'), node('Persist and apply', 'Durable state supports repeatable state-machine execution.'), node('Recover and validate', 'Operational recovery must retain the agreement invariants.')],
    glossary: [term('State-machine replication', 'Running the same deterministic command sequence on multiple replicas.'), term('Crash recovery', 'Restarting a failed process using durable state to preserve its prior obligations.')],
    exercise: exercise('An acceptor loses its promise record and rejoins as if it were new. Why is this more serious than a temporarily unreachable acceptor?', 'It might accept a proposal it had already promised to reject, violating the proof assumptions. Recovery must establish trustworthy state and safe participation; merely restarting the process does not repair forgotten protocol history.'),
    related: [related('paxos-simple', 'Read the invariant the production implementation must continue to honor.'), related('chubby', 'See the operational service interface built above consensus.')],
  },
  'paxos-simple': {
    shortTitle: 'Paxos Made Simple',
    problem: 'Processes can fail and messages can be delayed, yet a group must not choose two different values for one agreement instance.',
    ideas: ['A prepare phase obtains promises and previously accepted proposals from a majority. Proposal numbers order attempts.', 'A proposer must carry forward the value of the highest-numbered accepted proposal returned by its prepare quorum, if one exists; accept quorums then preserve chosen values.'],
    tradeoffs: ['Safety does not imply guaranteed progress under arbitrary asynchronous timing. Competing proposers can continually preempt one another.', 'One consensus instance chooses one value. A replicated log needs multiple instances, durable acceptor state, and further handling for reads and membership.'],
    prerequisites: ['Majority intersection', 'Message delay and crash failures'],
    readingNotes: ['Derive the value-selection rule from the desired safety property before memorizing message names.', 'Trace accepted versus chosen versus learned values separately, then read the progress and state-machine sections.'],
    diagram: [node('Prepare', 'Collect promises and accepted proposal history from a majority.'), node('Select safely', 'Reuse the highest-numbered accepted value returned, when present.'), node('Accept and learn', 'A majority acceptance chooses the value; learners discover it.')],
    glossary: [term('Promise', 'An acceptor commitment not to accept proposals below a specified number.'), term('Chosen value', 'A value whose proposal has been accepted by a majority in one instance.')],
    exercise: exercise('In a three-acceptor group, A and B accepted value x at proposal 7. Proposal 8 prepares at B and C. May it choose a new y?', 'No if B reports proposal 7 as the highest accepted proposal in that prepare response set. The new proposer must use x. B is the intersecting witness, even if nobody has yet informed a learner that x was chosen.'),
    related: [related('raft', 'Compare a log-oriented presentation of leader-based consensus.'), related('paxos-made-live', 'Follow the proof obligations into persistence and production recovery.')],
  },
  quic: {
    shortTitle: 'QUIC transport guide',
    problem: 'Applications need secure multiplexed transport without forcing every stream to wait for a missing byte on an unrelated stream, and need continuity across some network-path changes.',
    ideas: ['Provide independently ordered streams over a UDP-based connection with explicit flow control and secure transport integration.', 'Use connection IDs and validated path migration so connection identity is not limited to one fixed address tuple.'],
    tradeoffs: ['Independent stream delivery does not eliminate connection-wide congestion effects. Loss can still reduce the sending rate available to every stream.', 'RFC 9000 defines transport. TLS integration and loss recovery are companion specifications, and replay-sensitive use of early data needs separate application reasoning.'],
    prerequisites: ['TCP byte streams and UDP datagrams', 'Flow control versus congestion control'],
    readingNotes: ['Start with streams, connection IDs, and packet structure in RFC 9000.', 'Trace loss on one stream and then path migration. Keep byte ordering, congestion response, and security validation as separate mechanisms.'],
    diagram: [node('Multiplex streams', 'Frames carry offsets and data for independently ordered streams.'), node('Carry packets', 'Encrypted transport packets share connection-level network resources.'), node('Deliver per stream', 'Available stream data can progress without unrelated missing stream bytes.')],
    glossary: [term('Stream offset', 'The position of bytes within one ordered QUIC stream.'), term('Connection ID', 'An identifier that helps route packets to a connection across address changes.')],
    exercise: exercise('A packet containing stream A data is lost; a later packet contains stream B data. Must B wait for A retransmission?', 'Not solely to satisfy stream ordering. B can be delivered if its own needed bytes are present, while shared congestion control can still slow future traffic. Distinguish this from application dependencies between A and B.'),
    related: [related('trickle', 'Compare stream isolation with controlling bursts in TCP video delivery.'), related('anycast-load-balancing', 'Consider what happens when routing selects a different serving node.')],
  },
  sundial: {
    shortTitle: 'Sundial',
    problem: 'Datacenter applications need bounded time uncertainty even while synchronization links, devices, or clock domains fail. Excellent normal-case precision alone is insufficient.',
    ideas: ['Use frequent hardware synchronization messages for fast detection of failures that could invalidate a time bound.', 'Precompute backup synchronization plans with a graph-based algorithm so recovery need not discover a new plan from scratch.'],
    tradeoffs: ['Reported uncertainty bounds depend on hardware, topology, and the modeled failure cases. They are not a promise for arbitrary hosts over the public Internet.', 'A backup parent must avoid the failed dependency, not simply have a different address. Shared upstream clock domains can correlate failures.'],
    prerequisites: ['Clock offset, drift, and uncertainty', 'Network failure domains'],
    readingNotes: ['Read the failure model and uncertainty requirements before the synchronization graph algorithm.', 'Trace detection and switchover for one link failure, then compare with a domain failure. Keep measured precision separate from a justified uncertainty bound.'],
    diagram: [node('Synchronize', 'Hardware exchanges establish and maintain a clock relationship.'), node('Detect failure', 'Missing or invalid synchronization triggers recovery.'), node('Use backup plan', 'A precomputed alternative restores synchronization within stated bounds.')],
    glossary: [term('Time uncertainty', 'A bound on the possible difference between reported and reference time.'), term('Clock domain', 'A set of clock dependencies that can share a common failure.')],
    exercise: exercise('Two backup parents both depend on the same failed upstream clock. Do they provide independent recovery?', 'No. Draw their dependency paths and identify the common domain. A useful alternative must survive the relevant failure scenario, not merely be a second local neighbor.'),
    related: [related('spanner', 'See why bounded clock uncertainty affects transaction commit latency.'), related('jupiter-rising', 'Connect synchronization dependencies to a datacenter network topology.')],
  },
  'thread-per-core-tail-latency': {
    shortTitle: 'Shard-per-core topic guide',
    problem: 'A shared-memory database can spend substantial time on locks, cache-line movement, and scheduling. Avoiding those costs requires deliberate ownership of data and work.',
    ideas: ['The ScyllaDB architecture assigns data and execution to shards associated with CPU cores, reducing shared mutable state.', 'Use asynchronous I/O and explicit cross-shard communication rather than allowing a blocking operation to stall unrelated work on the owning core.'],
    tradeoffs: ['One overloaded shard can create high latency while other cores are idle. Aggregate CPU utilization hides this imbalance.', 'Core affinity does not remove queueing, storage latency, or cross-shard costs. Cooperative execution still needs bounded work units and effective scheduling.'],
    prerequisites: ['CPU caches and lock contention', 'Asynchronous I/O and queues'],
    readingNotes: ['The source is a living vendor architecture overview, not a paper named after the local demo.', 'Read shard-per-core, networking, and memory ownership together. Evaluate latency claims with an explicit workload and per-shard measurements.'],
    diagram: [node('Route to owner', 'A request reaches the core that owns its shard.'), node('Execute locally', 'Shard-local state avoids unnecessary shared-memory coordination.'), node('Await asynchronously', 'I/O and cross-shard messages complete without blocking the entire reactor.')],
    glossary: [term('Shard-per-core', 'Partitioning data and execution ownership across CPU cores.'), term('Reactor', 'An event-driven loop that schedules ready work and I/O completions.')],
    exercise: exercise('Eight cores show 25% average utilization, but one is saturated. Why can p99 latency still be poor?', 'Requests assigned to the saturated shard queue there even though the average looks healthy. Inspect per-shard arrival rates, service times, and hot keys; moving work or data may cost more than simply enabling another thread.'),
    related: [related('tail-at-scale', 'Connect hidden local stalls with user-visible latency tails.'), related('parallelism-optimizing-data-placement', 'Compare core ownership with spreading each query across machines.')],
  },
  trickle: {
    shortTitle: 'Trickle',
    problem: 'Bursty video transfers fill router queues and trigger loss even when the application only needs a steadier playback rate.',
    ideas: ['Apply a server-side upper bound to the TCP congestion window based on a target streaming rate and measured round-trip time.', 'Keep TCP congestion control while shaping the application delivery pattern to reduce bursts and unnecessary queueing.'],
    tradeoffs: ['A window cap controls permitted in-flight data, not exact packet departure times. It is not a hard guarantee of constant-rate delivery.', 'The target must sustain the playback buffer under changing RTT and available bandwidth. Reducing bursts must be evaluated alongside underrun risk.'],
    prerequisites: ['TCP congestion windows', 'Bandwidth-delay product and playback buffers'],
    readingNotes: ['Read how the application rate and RTT determine the cap, then distinguish that cap from TCP congestion response.', 'Inspect loss, RTT, and video buffer underrun metrics together in the production evaluation. The paper is about TCP delivery, not QUIC internals.'],
    diagram: [node('Choose video rate', 'The application determines the desired delivery rate.'), node('Estimate in-flight budget', 'Rate and RTT inform a congestion-window upper bound.'), node('Observe playback', 'Evaluate network loss, delay, and buffer health together.')],
    glossary: [term('Congestion window', 'TCP sender limit on outstanding data governed by congestion control.'), term('Buffer underrun', 'Playback exhausts available video data before more arrives.')],
    exercise: exercise('For an illustrative 2 MB/s rate and 50 ms RTT, what in-flight data corresponds to rate × RTT?', 'About 0.1 MB, using decimal units. This is a dimensional estimate, not the complete Trickle algorithm: headers, changing RTT, packetization, congestion, and buffering policy still matter.'),
    related: [related('quic', 'Separate congestion behavior from multiplexed stream delivery.'), related('tail-at-scale', 'Relate reduced queueing to application-visible latency variability.')],
  },
  'web-search-for-a-planet': {
    shortTitle: 'Web Search for a Planet',
    problem: 'A search service must answer many independent requests while also searching a huge index for each individual request, using cost-effective hardware that can fail.',
    ideas: ['Exploit inter-query parallelism by serving different requests on different processors and intra-query parallelism by partitioning the index.', 'Use software fault tolerance and replicated serving capacity to make commodity machines a practical cluster architecture.'],
    tradeoffs: ['A query that fans out to many shards can be dominated by the slowest necessary response. Healthy average machine latency is insufficient.', 'Hardware cost must be considered alongside power, networking, and operational reliability. The 2003 cluster description is historical, not a current deployment inventory.'],
    prerequisites: ['Index partitioning and replication', 'Parallel speedup and tail latency'],
    readingNotes: ['Identify where the design uses partitioning to serve one query and replication to serve many queries.', 'Then read the hardware and cost arguments. Keep workload structure central instead of generalizing commodity hardware as always optimal.'],
    diagram: [node('Accept query', 'A serving path receives one of many independent requests.'), node('Fan out index work', 'Index partitions search their portion in parallel.'), node('Merge response', 'Results are combined and returned under a latency budget.')],
    glossary: [term('Inter-query parallelism', 'Running different user queries at the same time.'), term('Intra-query parallelism', 'Using multiple workers to answer one query.')],
    exercise: exercise('Each of 100 independent shards meets a latency target with probability 0.99. What is the probability all meet it?', 'Under that simplifying independence assumption, 0.99^100 is about 36.6%. Real shard delays can be correlated. The calculation motivates examining fan-out tails rather than inferring query reliability from a single shard.'),
    related: [related('google-search-anatomy', 'Study what retrieval work the serving cluster must execute.'), related('tail-at-scale', 'Follow the later analysis of tail amplification in large services.')],
  },
  'jupiter-rising': {
    shortTitle: 'Jupiter Rising',
    problem: 'Datacenter compute growth needs affordable network bandwidth without relying on an ever-larger single switching chassis or arbitrary Internet routing machinery.',
    ideas: ['Build multi-stage Clos networks from commodity switch silicon with many parallel paths between endpoints.', 'Use centralized configuration and control suited to a preplanned, single-operator topology, combined with modular hardware and robust software.'],
    tradeoffs: ['Nominal port bandwidth is not guaranteed application throughput. Oversubscription, path imbalance, and failed links can create bottlenecks.', 'Central planning simplifies some routing problems but increases the importance of safe configuration rollout and control-plane fault handling.'],
    prerequisites: ['Switching and multi-path routing', 'Bisection bandwidth'],
    readingNotes: ['Read the three recurring design themes and follow how they evolve across network generations.', 'Compare topology capacity with the failure and operational discussion. The small local spine-leaf lab is an illustrative model, not a Jupiter topology reconstruction.'],
    diagram: [node('Attach servers', 'Edge switches connect racks to a multi-stage fabric.'), node('Distribute paths', 'Multiple fabric paths provide aggregate capacity and alternatives.'), node('Coordinate configuration', 'A planned control system manages the fabric as one deployment.')],
    glossary: [term('Clos topology', 'A multi-stage switching network built from smaller switching elements.'), term('Bisection bandwidth', 'The bandwidth available across a division of a network into two halves.')],
    exercise: exercise('Four equal uplinks supply 40 Gb/s total. One fails while offered cross-rack traffic is 35 Gb/s. What changes?', 'Remaining nominal capacity is 30 Gb/s, leaving at least 5 Gb/s of excess offered load in this simplified cut. Path imbalance can make the practical result worse. Extra routes do not create bandwidth beyond the surviving links.'),
    related: [related('inside-google-datacenters', 'Put network capacity within shared rack, power, and facility failure domains.'), related('borg', 'Connect workload placement to the network resources it consumes.')],
  },
  autopilot: {
    shortTitle: 'Autopilot',
    problem: 'Humans often over-reserve CPU and memory to avoid throttling and out-of-memory failures. Across a fleet, that caution leaves substantial unused capacity.',
    ideas: ['Use historical workload behavior and tuned recommendation methods to adjust task resource limits and job parallelism.', 'Optimize resource slack while considering CPU throttling and memory failure costs separately; make recommendations and adoption workflows operationally usable.'],
    tradeoffs: ['Past demand may not predict a rollout, burst, or changed dataset. Resource recommendations need observation and correction after deployment.', 'CPU can often degrade through throttling, while insufficient memory can kill a task. One symmetric utilization target cannot represent both failure costs.'],
    prerequisites: ['Resource requests and limits', 'Feedback loops and demand history'],
    readingNotes: ['Read vertical and horizontal scaling as separate controls, then examine the recommendation mechanisms.', 'Compare slack and OOM outcomes together, and read the adoption discussion. The local toy controls are not the production predictor or its evaluation.'],
    diagram: [node('Observe executions', 'Collect resource demand and failure history.'), node('Recommend resources', 'Choose task sizing or parallelism with workload-specific risk.'), node('Apply and reassess', 'Observe the resulting slack, throttling, and memory failures.')],
    glossary: [term('Slack', 'The difference between provisioned resource limits and actual resource use.'), term('Vertical scaling', 'Changing resources allocated to individual tasks rather than their count.')],
    exercise: exercise('A job uses 1 core most of the day and 4 during a short critical burst. Should its CPU limit simply become the mean?', 'Not without a latency and throttling objective. Compare burst duration, demand predictability, and the value of reserved headroom. Repeat the analysis separately for memory because an OOM kill has different consequences.'),
    related: [related('borg', 'Separate selecting resource sizes from placing tasks on machines.'), related('sre-capacity-management', 'Connect task recommendations to long-horizon fleet capacity plans.')],
  },
  'inside-google-datacenters': {
    shortTitle: 'Datacenter capacity topic guide',
    problem: 'A service capacity plan must survive shared infrastructure failures and physical constraints, rather than merely adding up healthy-server CPU totals.',
    ideas: ['Use the official datacenter overview to connect computing infrastructure with facilities, security, and sustainability responsibilities.', 'In the companion worksheet, model rack-level compute and network constraints explicitly and reserve headroom for a chosen failure scenario.'],
    tradeoffs: ['The corporate overview publishes no topology or per-rack capacity dataset for this exercise. All worksheet numbers are editorial assumptions.', 'Independent server-failure arithmetic cannot represent shared power, cooling, rack, or network failures. Surviving compute is useful only if the network and storage can support it.'],
    prerequisites: ['Capacity units and bottlenecks', 'Correlated failure domains'],
    readingNotes: ['Treat the source as an undated institutional overview, not a research paper or a precise bill of materials.', 'Before using the native model, write down assumed rack sizes, failure scope, and network limits. Compare assumptions with evidence rather than attributing the toy topology to Google.'],
    diagram: [node('Inventory constraints', 'List compute, network, power, and cooling assumptions.'), node('Remove a domain', 'Apply an explicit rack or shared-infrastructure failure.'), node('Check usable capacity', 'Recalculate the limiting resource and remaining headroom.')],
    glossary: [term('Failure domain', 'Components that can be disabled together by one event.'), term('Headroom', 'Capacity reserved above present demand to absorb growth, bursts, or failures.')],
    exercise: exercise('Four racks each provide 100 compute units, and demand is 280. After one rack fails, what remains, and is that enough to promise service?', '300 nominal units remain with 20 units of compute headroom. Check whether demand can be redistributed and whether network, storage, and other shared constraints still support it. The arithmetic alone is not an availability guarantee.'),
    related: [related('jupiter-rising', 'Study a published network design rather than assuming one from the facility overview.'), related('sre-capacity-management', 'Turn failure-aware demand into an explicit provisioning plan.')],
  },
};
