// Source-grounded editorial workspaces. Citation records remain in legacyPaperCitations.js.
const node = (label, detail) => ({ label, detail });
const term = (term, definition) => ({ term, definition });
const related = (id, reason) => ({ id, reason });
const exercise = (prompt, guidance) => ({ prompt, guidance });

export const legacyStorageGuides = {
  gfs: {
    shortTitle: 'GFS',
    problem: 'Large sequential reads and append-heavy processing must continue despite frequent commodity-machine failures. A conventional small-file filesystem contract is a poor fit for this workload.',
    ideas: ['Keep namespace and chunk-placement metadata at a master while clients transfer file data directly with chunkservers.', 'A leased primary orders mutations among replicas. Record append permits duplicates so concurrent producers can make progress without coordinating file offsets.'],
    tradeoffs: ['Large chunks reduce metadata overhead but a small hot file can concentrate load. The workload assumption matters as much as replication count.', 'Successful record append is not an exactly-once application transaction. Consumers must recognize padding and duplicate records; arbitrary writes have different consistency outcomes.'],
    prerequisites: ['Replication and leases', 'Sequential I/O and append workloads'],
    readingNotes: ['Read the assumptions and consistency model before the architecture. Separate namespace atomicity from the state of a mutated file region.', 'Trace control messages and data flow separately through a write, then read record append and stale-replica detection.'],
    diagram: [node('Locate', 'The master supplies chunk handles and replica locations.'), node('Stage bytes', 'The client pushes data through the chunkserver pipeline.'), node('Order mutation', 'The primary assigns an order and secondaries apply that order.')],
    glossary: [term('Chunk handle', 'Stable identifier for a chunk independent of its replica locations.'), term('Record append', 'An operation that lets the service choose an offset and may insert a record more than once.')],
    exercise: exercise('A producer times out after a record append was applied. It retries successfully. What must a log consumer do?', 'Accept that two physical records can represent one logical event. Give events stable identifiers and deduplicate at the application boundary. A timeout does not prove that the first append had no effect.'),
    related: [related('colossus', 'Compare the later metadata and storage architecture with the original master design.'), related('mapreduce', 'Connect large sequential file access to the execution model built above it.')],
  },
  bigtable: {
    shortTitle: 'Bigtable',
    problem: 'Web-scale applications need structured, sparse data with controllable locality, without requiring a full relational schema and general cross-row transactions.',
    ideas: ['Model data as a sorted map indexed by row key, column key, and timestamp. Row-key design determines which accesses are naturally adjacent.', 'Partition row ranges into tablets. A commit log, memtable, and immutable SSTables separate durable writes from compacted read structures.'],
    tradeoffs: ['Atomic operations on one row do not imply atomic transactions across arbitrary rows. Group related updates intentionally.', 'Sequentially increasing keys can funnel writes into one tablet even when total storage is balanced. Compaction also consumes resources while serving live traffic.'],
    prerequisites: ['Sorted key-value maps', 'Write-ahead logging and immutable files'],
    readingNotes: ['Sketch the three-dimensional data model and version-retention rules before following tablet assignment.', 'Follow a write through the commit log and memtable, then a read across memory and SSTables. Inspect locality groups and compaction as distinct optimizations.'],
    diagram: [node('Choose row', 'The sorted row key determines the tablet range.'), node('Log and buffer', 'Durable logging precedes serving the update from memory.'), node('Flush and compact', 'Immutable tables are merged while preserving visible versions.')],
    glossary: [term('Tablet', 'A partition covering a contiguous range of row keys.'), term('Locality group', 'Column families grouped into separate physical storage for selective access.')],
    exercise: exercise('All clients use the current timestamp as the start of their row key. Why might adding tablet servers fail to relieve a write hotspot?', 'New keys continue landing at one end of the ordered key space. A bucketed prefix can distribute writes, but a time-range query must then merge results from several buckets. State that read-path cost explicitly.'),
    related: [related('myrocks', 'Compare buffering and compaction in another sorted-file storage engine.'), related('spanner', 'Contrast single-row atomicity with distributed transactions and SQL.')],
  },
  spanner: {
    shortTitle: 'Spanner',
    problem: 'A globally replicated database must order transactions consistently with real-time observations while allowing useful reads across distant replicas.',
    ideas: ['Replicate shards with Paxos and coordinate transactions across participating groups; consensus and atomic commit solve different problems.', 'TrueTime exposes a bounded uncertainty interval. Commit wait ensures the chosen timestamp is in the past before a transaction reports success.'],
    tradeoffs: ['Clock uncertainty is an explicit input to latency, not an assumption of perfectly synchronized clocks. A wider bound can mean a longer wait.', 'Wide-area replication and multi-participant commit still pay communication and locking costs. Accurate time does not eliminate quorums or failure recovery.'],
    prerequisites: ['Paxos replication', 'Two-phase commit and multiversion reads'],
    readingNotes: ['Use the linked 2013 journal edition. Trace timestamp assignment and commit wait in the transaction discussion.', 'Distinguish a read at an old safe timestamp from a read that must observe the latest state. Do not equate every read with a leader round trip.'],
    diagram: [node('Replicate and prepare', 'Participants protect and replicate the transaction state.'), node('Assign timestamp', 'Choose a commit timestamp consistent with the ordering rules.'), node('Wait and publish', 'Wait out uncertainty before making success externally visible.')],
    glossary: [term('External consistency', 'Transaction order agrees with the real-time order of non-overlapping transactions.'), term('Commit wait', 'Delay until the time API can establish that a commit timestamp has passed.')],
    exercise: exercise('A transaction chooses timestamp 100. The earliest possible current time is 97. May it finish commit wait now?', 'No. The earliest possible current time must pass the chosen timestamp. Recheck the time interval rather than sleeping for an assumed fixed amount. This example omits replication and lock delays.'),
    related: [related('megastore', 'Compare entity-group replication with the later transaction design.'), related('sundial', 'Separate a clock-synchronization mechanism from the database contract using time.')],
  },
  dynamo: {
    shortTitle: 'Dynamo',
    problem: 'A shopping-cart service should accept useful writes during server failures and partitions, even when it cannot immediately agree on one value everywhere.',
    ideas: ['Distribute keys with consistent hashing and use configurable read and write response thresholds rather than a single fixed availability contract.', 'Track causal versions with vector clocks, reconcile concurrent siblings, and repair replica divergence using hinted handoff and anti-entropy.'],
    tradeoffs: ['R + W > N is not a blanket linearizability guarantee, especially with sloppy quorums, concurrent writes, and changing replica sets.', 'Availability moves conflict-resolution responsibility to the application. Merging carts can preserve additions while unexpectedly restoring a deleted item.'],
    prerequisites: ['Quorum intersection', 'Causality and concurrent versions'],
    readingNotes: ['Start with the application requirements and failure model rather than treating Dynamo as a relational database.', 'Track a version through put, get, reconciliation, and repair. Compare normal replica placement with temporary hinted storage.'],
    diagram: [node('Coordinate', 'A coordinator routes a key to a preference list of replicas.'), node('Collect versions', 'Response thresholds allow operation with some nodes unavailable.'), node('Reconcile and repair', 'Causal siblings are merged and divergent replicas converge.')],
    glossary: [term('Sloppy quorum', 'Using available nodes from a preference list rather than only the usual replica owners.'), term('Vector clock', 'Per-participant version information used to distinguish causal succession from concurrency.')],
    exercise: exercise('A and B both read cart version v. A adds tea while B removes milk. Can last-write-wins preserve both intentions?', 'Not reliably: selecting one entire cart discards the other edit. Describe an application merge rule and how deletions are represented. Causal metadata detects concurrency but does not decide business meaning.'),
    related: [related('paxos-simple', 'Contrast choosing one value with accepting and later reconciling concurrent versions.'), related('bigtable', 'Compare a sorted partitioned store with a different data and consistency model.')],
  },
  f1: {
    shortTitle: 'F1',
    problem: 'A business with an existing relational application needs scalable, highly available storage without abandoning SQL, schemas, and transactional correctness.',
    ideas: ['Build the relational layer on Spanner, reusing synchronous replication and strong consistency instead of inventing a separate storage protocol.', 'Use hierarchical schemas and application batching to improve locality and amortize remote access; combine distributed SQL with change tracking.'],
    tradeoffs: ['Hierarchical locality favors access within a root entity. Cross-root joins and transactions still require distributed work.', 'Moving an application to a distributed SQL system does not preserve single-machine latency. Repeated small remote operations can dominate a request.'],
    prerequisites: ['Relational joins and transactions', 'Spanner replication'],
    readingNotes: ['Read the schema hierarchy and application-design discussion together: the schema is part of the latency strategy.', 'Separate storage guarantees inherited from Spanner from F1 query execution and change-publication features.'],
    diagram: [node('Model hierarchy', 'Related rows share a useful root and storage locality.'), node('Execute SQL', 'The query layer distributes relational work.'), node('Commit and track', 'Spanner commits state and F1 supports observing changes.')],
    glossary: [term('Root entity', 'Top-level row around which a hierarchy of related rows is organized.'), term('Change tracking', 'Recording database changes so downstream consumers can observe them.')],
    exercise: exercise('A page performs 40 dependent database calls taking 8 ms each. What latency floor can batching remove, and what does batching not fix?', 'The serial call component is 320 ms before other work. Fewer remote calls can reduce it, but batching does not eliminate commit latency, cross-root coordination, or the cost of reading unnecessary data.'),
    related: [related('spanner', 'Read the storage and transaction substrate below the SQL layer.'), related('relational-model', 'Connect logical independence with a physical hierarchy chosen for locality.')],
  },
  myrocks: {
    shortTitle: 'MyRocks foundations',
    problem: 'A MySQL deployment with write-heavy data needs a storage engine that can reduce space and write costs while preserving the surrounding SQL application interface.',
    ideas: ['Integrate RocksDB as a MySQL storage engine, separating SQL processing from an LSM-based persistence layer.', 'Buffer updates and merge sorted files so random logical writes become larger physical operations; compression and key layout influence storage cost.'],
    tradeoffs: ['Reduced space or write amplification is a workload-dependent claim. Extra read probes and compaction can shift the bottleneck.', 'A storage-engine substitution is not a promise that every InnoDB feature, locking behavior, or operational procedure is interchangeable. Check the deployed version.'],
    prerequisites: ['MySQL storage engines', 'LSM write and read paths'],
    readingNotes: ['Treat the project homepage as an overview, not a dated experiment or a reproducible benchmark.', 'Use its documentation links to check feature compatibility before interpreting the advertised efficiency ratios.'],
    diagram: [node('Issue SQL', 'MySQL plans and executes application queries.'), node('Use engine', 'MyRocks maps storage operations into RocksDB.'), node('Maintain files', 'Flush and compaction reorganize durable sorted data.')],
    glossary: [term('Storage engine', 'The component implementing table persistence and access below SQL execution.'), term('Write amplification', 'Physical bytes written divided by logical bytes written for a defined interval.')],
    exercise: exercise('A migration halves data size but doubles p99 point-read latency. Is it a successful migration?', 'Only relative to an explicit service objective and cost budget. Measure cache state, read amplification, compaction contention, and sustained throughput. Storage savings alone do not establish an acceptable user experience.'),
    related: [related('myrocks1', 'Continue from engine selection into a concrete tuning worksheet.'), related('bigtable', 'Compare another log, memory, and sorted-file write path.')],
  },
  myrocks1: {
    shortTitle: 'MyRocks tuning guide',
    problem: 'After selecting an LSM engine, operators must choose memory, compaction, and indexing policies without optimizing one amplification measure at the expense of live latency.',
    ideas: ['Use the project wiki as a version-sensitive operational reference; establish workload shape and supported features before changing options.', 'Reason jointly about read, write, and space amplification. Measure steady-state compaction debt rather than only the fast initial loading phase.'],
    tradeoffs: ['More write buffering can postpone disk work and increase memory pressure. A short benchmark can end before the deferred work becomes visible.', 'Filters help negative lookups but cannot remove the cost of fetching actual rows. Secondary indexes also add write and storage work.'],
    prerequisites: ['MyRocks foundations', 'Cache hit rates and compaction'],
    readingNotes: ['Use the wiki navigation for the feature or option under study and record its applicable release in your notes.', 'The cited repository is archived. Do not read its home-page edit date as a publication date or assume its defaults describe a current fork.'],
    diagram: [node('Baseline', 'Record query mix, dataset size, cache state, and current options.'), node('Change one policy', 'Alter a measured bottleneck such as filtering or compaction capacity.'), node('Observe steady state', 'Check latency, amplification, stalls, and recovery before accepting the change.')],
    glossary: [term('Compaction debt', 'Pending file-reorganization work accumulated faster than it can be completed.'), term('Read amplification', 'Extra storage work required to answer one logical read.')],
    exercise: exercise('Ingest initially sustains 80 MB/s but compaction processes only 50 MB/s of required work. What must a credible tuning trial include?', 'A run long enough to reveal accumulating debt, write stalls, disk use, and read interference. The two rates need a common work unit before subtraction; logical ingest bytes and physical compaction bytes are not automatically comparable.'),
    related: [related('myrocks', 'Return to the engine-selection problem and compatibility boundaries.'), related('bloom-paradox', 'Estimate when negative-lookup filters repay their memory and CPU cost.')],
  },
  'relational-model': {
    shortTitle: 'The relational model',
    problem: 'Programs that depend on physical record order or pointer paths break when a shared database changes its representation. Users need a logical model independent of those choices.',
    ideas: ['Describe data as relations rather than embedding access paths into the logical interface.', 'Use relational operations and constraints to reason about derivability, redundancy, and consistency separately from physical storage.'],
    tradeoffs: ['Logical independence does not make every query cheap. An implementation still chooses indexes, access paths, and join algorithms.', 'The 1970 model is not identical to modern SQL: duplicates, NULL semantics, and ordering require additional care when translating examples.'],
    prerequisites: ['Sets, tuples, and keys', 'Basic database queries'],
    readingNotes: ['Read data independence and the contrast with network models first. Identify what a user no longer needs to know.', 'Then examine redundancy and consistency; keep the original normal-form discussion separate from later normalization theory.'],
    diagram: [node('Describe relation', 'Name attributes and constraints without choosing pointer paths.'), node('Express operation', 'State the required result over logical relations.'), node('Choose access path', 'An implementation supplies physical execution independently.')],
    glossary: [term('Data independence', 'Insulating logical use of data from changes to its physical representation.'), term('Relation', 'A set of tuples over specified domains, with no intrinsic row order.')],
    exercise: exercise('A customer table moves from a heap to a B-tree. Which application assumption violates data independence?', 'Assuming that the fifth stored record is a particular customer. Query by a logical key instead. Even an index-backed SQL query needs an explicit ordering clause if presentation order matters.'),
    related: [related('f1', 'See how a distributed SQL system combines a relational interface with deliberate physical locality.'), related('bigtable', 'Contrast a sorted-map interface with the relational abstraction.')],
  },
  'windows-azure-storage': {
    shortTitle: 'Windows Azure Storage',
    problem: 'A cloud storage service must provide strong consistency and availability while scaling namespace ownership and durable bytes independently.',
    ideas: ['Separate front-end request handling, partition ownership, and the stream layer that persists replicated extents.', 'Use storage stamps and distinguish replication inside a stamp from asynchronous replication across locations. These are different consistency and disaster-recovery boundaries.'],
    tradeoffs: ['Strong consistency inside the primary service does not imply zero data loss for an asynchronous remote copy after a regional disaster.', 'Partition rebalancing changes ownership, not just byte placement. A hot partition can remain a serving bottleneck even with abundant disk capacity.'],
    prerequisites: ['Replication versus partitioning', 'Strong consistency and asynchronous recovery'],
    readingNotes: ['Draw the three layers from the architecture section, then place each failure-recovery responsibility on the right layer.', 'Read intra-stamp and inter-stamp replication separately. Use the 2011 paper as a historical system description, not current Azure product documentation.'],
    diagram: [node('Front end', 'Authenticate and route an object request.'), node('Partition layer', 'Resolve ownership and enforce object-level operations.'), node('Stream layer', 'Persist and replicate the underlying extents.')],
    glossary: [term('Storage stamp', 'A deployment unit containing storage and serving resources.'), term('Extent', 'A unit of stream storage and replication below the object interface.')],
    exercise: exercise('A write is acknowledged locally, then the primary location fails before remote replication. Can the remote location guarantee that write is present?', 'Not from asynchronous replication alone. Separate acknowledgement durability within the stamp from recovery-point guarantees across stamps, and explain the availability versus data-loss decision during failover.'),
    related: [related('gfs', 'Compare metadata ownership with lower-level replicated file data.'), related('spanner', 'Contrast asynchronous remote recovery with synchronous wide-area transaction replication.')],
  },
  zanzibar: {
    shortTitle: 'Zanzibar',
    problem: 'Many services need low-latency authorization over shared relationships while ensuring a stale permission check cannot expose newly changed content.',
    ideas: ['Represent authorization with relationship tuples and a configuration language that composes permissions across objects and usersets.', 'Use consistency tokens to connect authorization snapshots to causal changes in content and permissions, rather than treating every cached allow decision as timeless.'],
    tradeoffs: ['A newer snapshot can require waiting or additional work. Low-latency cached evaluation must respect the requested consistency boundary.', 'The authorization engine cannot infer the application transaction that ties content to a permission change. Callers must propagate the appropriate token and context.'],
    prerequisites: ['Access-control lists and graph traversal', 'Causality and snapshot reads'],
    readingNotes: ['Read the new-enemy problem before the tuple syntax. Explain which stale decision becomes a confidentiality failure.', 'Trace a check through userset rewriting and the consistency interface. Separate the data model from evaluation optimizations.'],
    diagram: [node('Store relationships', 'Tuples and configuration define membership and permissions.'), node('Bind freshness', 'The request carries a required consistency boundary.'), node('Evaluate check', 'Resolve usersets at a sufficiently fresh snapshot.')],
    glossary: [term('Userset', 'A set of users described through an object relationship rather than only an explicit list.'), term('Zookie', 'An opaque consistency token used to constrain the freshness of authorization operations.')],
    exercise: exercise('An editor loses access, then a document receives confidential new text. Why can an old cached allow decision be unsafe?', 'It can authorize the removed editor to read content created after revocation. Bind the content operation to a suitable authorization freshness boundary. Merely shortening a cache TTL does not establish causal ordering.'),
    related: [related('spanner', 'Connect consistent authorization snapshots to their storage substrate.'), related('google-infrastructure-security', 'Place object authorization within a broader identity and service-security design.')],
  },
};
