const node = (label, detail) => ({ label, detail });
const term = (term, definition) => ({ term, definition });
const related = (id, reason) => ({ id, reason });
const exercise = (prompt, guidance) => ({ prompt, guidance });

export const legacyDataGuides = {
  mapreduce: {
    shortTitle: 'MapReduce',
    problem: 'Programmers need to process large datasets without implementing distributed scheduling, inter-machine transfer, and worker-failure handling in every application.',
    ideas: ['Express a computation as map emissions followed by grouping and reduction for each intermediate key.', 'The runtime partitions input, schedules near data, retries failed work, and uses backup tasks to reduce straggler impact.'],
    tradeoffs: ['A hot intermediate key can dominate one reducer despite balanced input splits. More workers do not split an indivisible reduce group automatically.', 'Retries may execute application code more than once. External side effects need a separate idempotency or commit protocol; output-file handling does not protect an arbitrary payment API.'],
    prerequisites: ['Key-value transformations', 'Partitioning and deterministic functions'],
    readingNotes: ['Follow the execution overview and then the failure-handling cases for map versus reduce workers.', 'Read locality, backup tasks, and combiners as different optimizations. A combiner must preserve reduction semantics even when applied zero or multiple times.'],
    diagram: [node('Map', 'Input splits produce intermediate key-value pairs.'), node('Shuffle', 'Partition and group all values for the same key.'), node('Reduce', 'Process each group and publish partitioned output.')],
    glossary: [term('Shuffle', 'Transfer and grouping of intermediate data between map and reduce stages.'), term('Backup task', 'A duplicate execution of slow remaining work used to mitigate stragglers.')],
    exercise: exercise('Can a mapper emit local averages and a reducer average those numbers to compute a global average?', 'Only if all groups have equal sizes. Emit sum and count, combine those pairs, then divide once. This also permits an optional combiner without depending on how often it runs.'),
    related: [related('gfs', 'Connect locality-aware scheduling to the underlying distributed files.'), related('flumejava', 'Extend individual jobs into optimized multi-stage pipelines.')],
  },
  flumejava: {
    shortTitle: 'FlumeJava',
    problem: 'A sequence of hand-managed MapReduce jobs exposes storage boundaries and scheduling details that obscure application logic and create redundant work.',
    ideas: ['Represent immutable parallel collections with a small set of composable operations rather than choosing physical jobs at each call site.', 'Defer evaluation to build a dataflow graph, optimize that graph, and lower it to appropriate execution primitives.'],
    tradeoffs: ['Deferred operations do not execute at their declaration point. Debugging must distinguish graph construction from remote execution.', 'Fusion can remove intermediate materialization, but some boundaries are needed for grouping, reuse, or failure recovery. Optimization must preserve user-visible semantics.'],
    prerequisites: ['MapReduce jobs', 'Lazy evaluation and dataflow graphs'],
    readingNotes: ['Map the collection API to a small logical pipeline before reading optimizer transformations.', 'Compare the logical graph with the optimized physical execution plan; count materializations rather than assuming one API call equals one job.'],
    diagram: [node('Compose', 'Build transformations over parallel collections.'), node('Optimize', 'Rewrite the deferred graph to reduce redundant work.'), node('Execute', 'Run physical primitives and materialize requested results.')],
    glossary: [term('Deferred evaluation', 'Recording an operation now and computing it when a result is requested.'), term('Fusion', 'Combining compatible operations into one physical execution stage.')],
    exercise: exercise('A pipeline reads rows, parses them, filters invalid rows, and maps to keys before grouping. Which operations could plausibly share a stage?', 'Parsing, filtering, and key construction can often execute together before the grouping boundary. Verify that transformations do not rely on external side effects or their original execution timing.'),
    related: [related('mapreduce', 'Identify the lower-level execution boundaries being hidden.'), related('rdd', 'Compare deferred collection operations and recovery through lineage.')],
  },
  'magnet-shuffle': {
    shortTitle: 'Magnet shuffle',
    problem: 'Large Spark jobs generate many tiny intermediate blocks. Fetching them independently creates random I/O and connection overhead that can dominate the shuffle.',
    ideas: ['Push intermediate output toward shuffle services that merge fragments into larger blocks for each reduce partition.', 'Co-locate merged blocks with reduce work where possible, reducing remote transfer and small-read overhead.'],
    tradeoffs: ['Merging changes the transfer and storage path; it does not reduce the logical number of records that a reducer must process.', 'Retries, incomplete merges, and stragglers require fallback and completeness accounting. A reducer must not silently omit a mapper or count a retried block twice.'],
    prerequisites: ['Spark stages and shuffle partitions', 'Sequential versus random disk access'],
    readingNotes: ['Use the VLDB paper to identify the small-block bottleneck, then trace push, merge, and reduce-side consumption.', 'Inspect fault handling and evaluation setup before applying production runtime improvements to a different network or disk configuration.'],
    diagram: [node('Produce partitions', 'Mappers generate fragments for many reducers.'), node('Push and merge', 'Shuffle services assemble larger partition blocks.'), node('Consume nearby', 'Reducers read merged data and account for unmerged fragments.')],
    glossary: [term('Shuffle fragment', 'One mapper contribution to one reduce partition.'), term('Merged block', 'A larger physical unit combining contributions destined for the same partition.')],
    exercise: exercise('A reducer needs outputs from 100 maps; 97 were merged and three arrived late. Is reading one merged file sufficient?', 'No. It must obtain the three missing contributions and know which map outputs the merged file contains. Retried map attempts must not introduce duplicates. Fewer reads must preserve the same logical input.'),
    related: [related('mapreduce', 'Return to the original shuffle contract before optimizing its physical path.'), related('rdd', 'Place shuffle services within the Spark execution and recovery model.')],
  },
  monarch: {
    shortTitle: 'Monarch',
    problem: 'Planet-scale monitoring needs fast ingestion and queries while avoiding a design where a single regional failure disables the entire monitoring service.',
    ideas: ['Regionalize data ingestion and in-memory serving for reliability and scale, with global query and configuration planes integrating the regions.', 'Use an expressive relational time-series model so monitoring queries can aggregate dimensions without losing the meaning of their measurements.'],
    tradeoffs: ['Global queries depend on regional answers and their freshness. A missing region must not be interpreted as zero traffic or zero errors.', 'High-cardinality dimensions multiply state and query work. In-memory serving requires explicit resource management rather than unlimited retention.'],
    prerequisites: ['Time-series labels and aggregation', 'Regional failure isolation'],
    readingNotes: ['Read the regionalized architecture first and draw the global control and query planes separately.', 'Then inspect configuration and query execution. Record which failure behavior is part of monitoring correctness, not merely a performance optimization.'],
    diagram: [node('Ingest regionally', 'Measurements enter nearby serving regions.'), node('Store and query', 'Regional time-series state supports low-latency evaluation.'), node('Combine globally', 'The query plane integrates regional results and their availability.')],
    glossary: [term('Cardinality', 'The number of distinct time series generated by combinations of labels.'), term('Regionalization', 'Partitioning service operation into regions to limit the scope of failures.')],
    exercise: exercise('Two regions report 2 errors in 100 requests and 90 errors in 900 requests. What is the global error ratio?', 'Use (2 + 90) / (100 + 900) = 9.2%, not the mean of 2% and 10%. If one region is unavailable, label the result partial instead of treating its missing counters as zero.'),
    related: [related('gorilla', 'Compare another in-memory monitoring store with emphasis on compression.'), related('sre-workbook', 'Connect correctly aggregated measurements to SLO decisions.')],
  },
  napa: {
    shortTitle: 'Napa',
    problem: 'Business-facing analytics must serve changing data with predictable low latency, even when different applications demand different freshness and cost settings.',
    ideas: ['Aggressively use materialized views maintained consistently during ingestion to move work out of interactive queries.', 'Expose configuration choices around freshness, performance, and resource use while supporting multi-datacenter availability.'],
    tradeoffs: ['Precomputation consumes ingestion, storage, and maintenance resources. A fast query is not free if many unused views are maintained.', 'A view helps only the queries its shape supports. New predicates or grouping dimensions can change the cost profile substantially.'],
    prerequisites: ['Materialized views and incremental aggregation', 'Analytical query planning'],
    readingNotes: ['Start with the demanding application constraints and why robust performance is a design target.', 'Follow ingestion into materialized views, then check how evaluation accounts for freshness and maintenance cost alongside query latency.'],
    diagram: [node('Ingest changes', 'Applications continuously supply new and updated data.'), node('Maintain views', 'Consistent derived structures precompute useful work.'), node('Serve queries', 'Queries select suitable representations within configured requirements.')],
    glossary: [term('Materialized view', 'A stored query result maintained as its underlying data changes.'), term('Freshness', 'How far query-visible data lags the relevant incoming changes.')],
    exercise: exercise('A daily total by country is precomputed. Can it answer an exact total by individual user?', 'Not if the user dimension was discarded. Return to a finer-grained representation or add another view, then account for its maintenance and storage. Fast aggregate lookup cannot recover information already removed.'),
    related: [related('mesa', 'Compare earlier geo-replicated analytical aggregation at Google.'), related('dremel', 'Contrast precomputation-heavy serving with interactive scans over nested columns.')],
  },
  'parallelism-optimizing-data-placement': {
    shortTitle: 'Parallelism-aware placement',
    problem: 'Equal total data and load per machine can still yield slow queries when the particular shards needed by one query are concentrated on a single host.',
    ideas: ['Optimize the spread of each query across machines, not just aggregate storage balance.', 'Use a workload-derived measure of query parallelism to formulate placement, and partition the optimization problem to scale the planning process.'],
    tradeoffs: ['Placement depends on a representative query workload. A changing access pattern can invalidate the plan even if stored bytes remain balanced.', 'Wider query participation can add network and coordination overhead. Parallelism is useful only when reduced local contention outweighs those costs.'],
    prerequisites: ['Sharded query execution', 'Tail latency and workload traces'],
    readingNotes: ['Read the opening placement example: the alternative layouts have balanced data but different per-query contention.', 'Then inspect the parallelism objective and experiments on Solr and MongoDB. Keep measured p99 improvements tied to the evaluated workloads.'],
    diagram: [node('Observe co-access', 'Record which shards each query needs together.'), node('Optimize placement', 'Spread co-accessed work across available machines.'), node('Validate tails', 'Measure per-query contention, network work, and p99 latency.')],
    glossary: [term('Query parallelism', 'The degree to which one query can use resources on multiple machines concurrently.'), term('Co-access', 'Two data items or shards being needed by the same query.')],
    exercise: exercise('Hosts A and B each store two equal shards. A stores x and y; every query needs x and y. What does moving y to B change?', 'The dominant query can now use both hosts instead of contending for one host. Keep storage balanced by exchanging a cold shard, and measure the new network cost. Equal shard counts alone never proved balanced query execution.'),
    related: [related('borg', 'Contrast workload placement with placement of the data that workload accesses.'), related('tail-at-scale', 'Connect per-query parallelism to end-to-end tail behavior.')],
  },
  pregel: {
    shortTitle: 'Pregel',
    problem: 'Graph algorithms repeatedly update vertices based on neighboring state. Encoding every iteration as unrelated batch jobs obscures persistent graph structure and communication.',
    ideas: ['Express computation from a vertex perspective: process incoming messages, update local state, and send messages for the next superstep.', 'Use barriers, active-vertex state, and checkpoint-based recovery to coordinate iterative execution. Combiners can reduce messages when their semantics permit it.'],
    tradeoffs: ['A superstep waits for participating workers. A straggler or unavailable partition prevents the next barrier from completing.', 'Graph degree skew and partition cuts determine load and communication. A balanced vertex count does not guarantee balanced work.'],
    prerequisites: ['Directed graphs', 'Bulk synchronous parallel execution'],
    readingNotes: ['Trace message visibility and vote-to-halt behavior before reading the fault-tolerance implementation.', 'For each algorithm, write the local vertex rule and its termination condition. The local shortest-path lab is one bounded example, not the entire runtime.'],
    diagram: [node('Compute locally', 'Active vertices consume messages from the prior superstep.'), node('Send messages', 'Updates target neighbors for the next superstep.'), node('Cross barrier', 'Workers complete the step before messages become visible.')],
    glossary: [term('Superstep', 'A synchronized round of computation and message production.'), term('Vote to halt', 'A vertex becomes inactive until a later message reactivates it.')],
    exercise: exercise('A reaches B in one hop and B reaches C in another. Starting only at A, can C learn its distance in the same superstep as B?', 'No in this message-passing model. B receives the first update in a later superstep and its message to C crosses another barrier. Trace the round numbers explicitly instead of propagating within one loop.'),
    related: [related('scaling-pagerank', 'Specialize repeated graph messaging when the communication pattern stays fixed.'), related('mapreduce', 'Compare graph-resident iteration with general batch grouping.')],
  },
  'scaling-pagerank': {
    shortTitle: 'Scaling PageRank',
    problem: 'Repeated PageRank iterations send contributions over the same edges, wasting bandwidth if each message repeatedly describes routing information already known to both sides.',
    ideas: ['Exploit the invariant communication pattern across supersteps to exchange edge payloads without repeatedly carrying full edge identity.', 'Treat communication representation as an optimization target independent of the PageRank update formula.'],
    tradeoffs: ['Stable topology and compatible message ordering are central assumptions. Arbitrary dynamic graphs cannot reuse the layout without maintenance.', 'The title describes a scale target; the abstract reports experiments on 38 billion vertices and 3.1 trillion edges. Neither is a universal throughput guarantee.'],
    prerequisites: ['PageRank iteration', 'Pregel-style graph messaging'],
    readingNotes: ['First identify what information can be agreed once and reused across iterations.', 'Then read the evaluated graph, machine configuration, and per-iteration timing. Compare bytes transferred as well as total execution time.'],
    diagram: [node('Prepare pattern', 'Establish the repeated edge communication layout.'), node('Exchange payloads', 'Transmit contributions using the shared layout.'), node('Iterate ranks', 'Update ranks and reuse the pattern for the next superstep.')],
    glossary: [term('Edge payload', 'The numerical contribution carried along a graph edge.'), term('Static communication pattern', 'The same sender-to-recipient relationships repeated across rounds.')],
    exercise: exercise('An edge is deleted between iterations but the receiver still uses the old payload ordering. What correctness risk appears?', 'A value can be attributed to the wrong edge or destination. Rebuild or version the communication layout, and include that maintenance cost when extending the static-graph design.'),
    related: [related('pregel', 'Start with the general superstep communication contract.'), related('google-search-anatomy', 'Separate computing global link authority from using it in a search engine.')],
  },
  'google-search-anatomy': {
    shortTitle: 'Anatomy of web search',
    problem: 'A web search engine must crawl, index, and rank an uncontrolled hypertext collection where matching query words alone is an inadequate relevance signal.',
    ideas: ['Combine text and positional evidence with hyperlink structure, including PageRank and anchor text.', 'Build a complete pipeline from crawling and parsing through index construction to query-time retrieval and ranking.'],
    tradeoffs: ['Link-derived authority is not equivalent to factual accuracy or a personalized relevance judgment. The early ranking design should not be presented as current Google Search.', 'Freshness depends on crawl and indexing progress; a fast serving path can still answer from an old corpus.'],
    prerequisites: ['Inverted indexes', 'Graphs and relevance scoring'],
    readingNotes: ['Use the system overview to separate offline indexing from online query processing.', 'Read PageRank and anchor text alongside the ranking discussion. Ask which signals are query-independent and which depend on the query.'],
    diagram: [node('Collect web pages', 'Crawl content and links into an indexed corpus.'), node('Build representations', 'Construct term hits, anchor evidence, and link-derived importance.'), node('Retrieve and rank', 'Combine matching evidence and ranking signals for the query.')],
    glossary: [term('Anchor text', 'The words of a hyperlink, which can describe its destination.'), term('PageRank', 'A link-based importance measure based on a random-surfer interpretation.')],
    exercise: exercise('A page contains no occurrence of a query word, but many links pointing to it use that word. Could it still be relevant in this design?', 'Yes. Anchor text supplies descriptive evidence about the target. Discuss when that helps, when misleading links could hurt, and why one signal cannot establish relevance alone.'),
    related: [related('idf-symbolic-sim', 'Study corpus-dependent lexical weighting before combining more signals.'), related('web-search-for-a-planet', 'Move from retrieval design to the cluster that serves queries.')],
  },
  'twitter-wtf': {
    shortTitle: 'Who to Follow',
    problem: 'A social service needs useful account recommendations from a huge follow graph while keeping the engineering path short enough to deploy and iterate.',
    ideas: ['The described first-generation service keeps the graph in memory on a single server using Cassovary, deliberately reducing distributed-system complexity.', 'Combine personalized random-walk neighborhoods with graph recommendation methods such as SALSA to find candidates, rather than simply returning the most popular users.'],
    tradeoffs: ['An in-memory single-server graph has a capacity ceiling. The paper discusses a later generation rather than claiming indefinite scale from this design.', 'Graph proximity is only evidence of likely interest. Cold-start users, stale relationships, and relevance evaluation require additional treatment.'],
    prerequisites: ['Directed follow graphs', 'Random walks and recommendation evaluation'],
    readingNotes: ['Read the architectural simplification and its limits before the graph algorithms.', 'Separate candidate generation, filtering, and evaluation. The recommendation score is not a calibrated probability that a user will follow.'],
    diagram: [node('Find neighborhood', 'Build a personalized circle of graph-relevant accounts.'), node('Score candidates', 'Use graph relationships to identify promising follow targets.'), node('Filter and serve', 'Remove unsuitable candidates and present recommendations.')],
    glossary: [term('Circle of trust', 'A personalized neighborhood used as a starting set for recommendation.'), term('SALSA', 'A link-analysis approach using walks on a hub-authority bipartite graph.')],
    exercise: exercise('A candidate has many global followers but no connection to a user neighborhood. Why might a less popular account rank higher?', 'The recommendation task is personalized interest, not global popularity. Explain the connecting paths and then propose an offline relevance metric plus an online follow-quality measurement.'),
    related: [related('scaling-pagerank', 'Contrast personalized graph neighborhoods with global iterative ranking.'), related('hnsw', 'Compare graph-based recommendation evidence with a graph used to accelerate vector search.')],
  },
  'idf-symbolic-sim': {
    shortTitle: 'TF-IDF topic guide',
    problem: 'A lexical search system needs to distinguish a document that mentions an informative term from one that merely repeats words common across the corpus.',
    ideas: ['Term frequency measures within-document occurrence, while inverse document frequency discounts terms found in many documents.', 'Keep tokenization, the weighting formula, and vector normalization explicit. TF-IDF names a family of weighting choices, not one universal score.'],
    tradeoffs: ['Bag-of-words representations discard word order and can confuse sentences with opposite meanings but identical term counts.', 'Rare terms are not necessarily useful terms: typos and identifiers can receive high weights. Corpus changes also change IDF.'],
    prerequisites: ['Logarithms and document counts', 'Vector similarity'],
    readingNotes: ['Read the linked term-frequency section and its next section on inverse document frequency.', 'Then inspect vector-space scoring and normalization in the book. Use a tiny hand-worked corpus rather than reproducing the whole textbook.'],
    diagram: [node('Count locally', 'Tokenize each document and count its terms.'), node('Weight globally', 'Compute document frequency across the selected corpus.'), node('Score explicitly', 'Combine TF and IDF with a stated normalization rule.')],
    glossary: [term('Document frequency', 'The number of documents containing a term at least once.'), term('Inverse document frequency', 'A corpus rarity weight, commonly log(N / df) for positive document frequency.')],
    exercise: exercise('In 100 documents, one term appears in 10 and another in all 100. Using log10(N / df), what are their IDFs?', 'They are 1 and 0. The ubiquitous term contributes zero under this unsmoothed formula. Name the log base and smoothing convention before comparing with a library implementation; this formula does not define a df = 0 case.'),
    related: [related('google-search-anatomy', 'Add link and positional evidence to lexical matching.'), related('rag', 'Connect retrieval evidence to a downstream generation system.')],
  },
  'photon-pubsub': {
    shortTitle: 'Photon stream joins',
    problem: 'Advertising streams arrive out of order and can be delayed or replayed across datacenters. Business metrics require joined events without duplicate output.',
    ideas: ['Maintain persistent join and identity state across geographically distributed processing so infrastructure failures do not require manual reconciliation.', 'Distinguish at-most-once output, near-exact real-time completeness, and eventual exactly-once joining. These describe different moments and properties of the result.'],
    tradeoffs: ['Low latency does not imply that all joinable events are present immediately. Delayed input and recovery affect completeness.', 'The historical local title also mentions Pub/Sub, a different system. Its delivery/deduplication lab illustrates one ingredient, not the complete Photon join protocol.'],
    prerequisites: ['Stream joins and event identity', 'Durable deduplication'],
    readingNotes: ['Read the abstract semantics carefully, then trace how persistent state supports joining across failures.', 'Choose one delayed event and one duplicate event and follow them separately. Do not replace the paper contract with a generic exactly-once messaging claim.'],
    diagram: [node('Receive streams', 'Events from related streams may be delayed, unordered, or repeated.'), node('Match persistently', 'Durable identity and join state connect corresponding events.'), node('Emit once', 'Produce unique joined results while late matches catch up.')],
    glossary: [term('Joinable event', 'An event for which the corresponding input needed by the join exists.'), term('Near-exact semantics', 'Most joinable output is available promptly, with eventual completeness handled separately.')],
    exercise: exercise('A click arrives now and its query record arrives ten minutes later. Is an empty immediate join output proof of data loss?', 'No. Distinguish missing input from permanently lost state. The system must preserve enough information to produce the match later without duplicating it after replay. State any retention assumptions in your design.'),
    related: [related('millwheel', 'Compare persistent state, retries, and progress tracking in stream processing.'), related('dataflow', 'Use the model to separate result completeness from emission timing.')],
  },
  'lambda-architecture': {
    shortTitle: 'Lambda architecture topic guide',
    problem: 'An analytics application wants both rapid updates and the ability to recompute correct results from a complete historical dataset after bugs or logic changes.',
    ideas: ['Keep a master dataset for batch recomputation and a speed path for data not yet reflected in batch views.', 'Serve a combination of views with an explicit coverage boundary; replace superseded speed results as batch processing catches up.'],
    tradeoffs: ['Two paths can duplicate business logic and diverge in subtle ways. Replayability does not excuse inconsistent definitions between them.', 'Overlapping coverage can double-count events. A cutoff must describe what the batch actually includes, not just the wall-clock time when a job ended.'],
    prerequisites: ['Batch and streaming aggregation', 'Replayable event histories'],
    readingNotes: ['The citation is the Big Data book, not a paper. Use its architecture overview to identify master data, batch views, speed views, and serving.', 'For a single metric, write the reconciliation rule before choosing technologies. The workspace offers an original exercise rather than a reproduction of book chapters.'],
    diagram: [node('Preserve history', 'Store input facts for future recomputation.'), node('Build two views', 'Batch covers committed history; speed covers newer data.'), node('Reconcile coverage', 'Serve a result without counting the overlap twice.')],
    glossary: [term('Batch view', 'A query-oriented result computed from a defined historical input set.'), term('Speed view', 'A low-latency result covering input not yet incorporated into the batch view.')],
    exercise: exercise('Batch includes event IDs 1 through 80; the speed view includes 70 through 100. How many unique events should a count return?', '100, not 111. Combine batch coverage with speed events 81 through 100, or use an equivalent deduplication rule. Real out-of-order streams need a more precise coverage contract than this ordered-ID toy example.'),
    related: [related('mapreduce', 'Explore the replayable batch-processing side of the architecture.'), related('dataflow', 'Compare a unified model for bounded and unbounded processing.')],
  },
  tensorflow: {
    shortTitle: 'TensorFlow systems paper',
    problem: 'Machine-learning developers need to express training algorithms, shared state, and computation placement across heterogeneous devices without hardwiring one parameter-server algorithm.',
    ideas: ['Represent computation and mutable state in a dataflow graph whose operations can run on CPUs, GPUs, and other devices.', 'Separate graph specification from placement and distributed execution, enabling different training and state-management strategies.'],
    tradeoffs: ['Placing more operations on accelerators can add expensive transfers. A graph with more parallelism is not automatically a faster graph.', 'The 2016 paper describes a historical execution model. A tiny gradient lab is not distributed TensorFlow and does not represent all modern eager-execution APIs.'],
    prerequisites: ['Computation graphs and gradients', 'Device memory and data transfer'],
    readingNotes: ['Read the dataflow and state model before looking at performance. Identify which edges carry tensors and which operations mutate parameters.', 'Then trace partitioning and cross-device communication. Treat application benchmarks as evaluated configurations rather than guarantees.'],
    diagram: [node('Define graph', 'Operations describe tensor computation and state updates.'), node('Place operations', 'Map graph nodes to available computational devices.'), node('Execute and transfer', 'Run dependencies and communicate tensors across device boundaries.')],
    glossary: [term('Tensor', 'A typed multidimensional array carried between operations.'), term('Placement', 'Assignment of an operation to a computational device.')],
    exercise: exercise('Two cheap operations surround one GPU operation. Why can moving all three to different devices be slower?', 'Synchronization and tensor transfer can exceed the compute savings. Estimate bytes crossing each boundary and compare transfer time with execution time before maximizing device-level parallelism.'),
    related: [related('federated-optimizations', 'Contrast datacenter device placement with training on decentralized client data.'), related('flashattention', 'Study a later optimization driven by memory traffic within an accelerator.')],
  },
  'federated-optimizations': {
    shortTitle: 'Federated averaging',
    problem: 'Useful training data resides on many devices and may be too sensitive or costly to centralize. Communication rounds are expensive compared with additional local computation.',
    ideas: ['Send a shared model to a subset of clients, perform local training, and aggregate the resulting model updates.', 'FedAvg uses data-size-weighted averaging while allowing multiple local steps, reducing communication relative to frequent synchronized updates in the evaluated settings.'],
    tradeoffs: ['Non-IID client data can make longer local training drift away from a useful global update. Fewer rounds alone do not prove equal model quality.', 'Keeping raw examples on devices is not a formal privacy guarantee. Model updates can leak information; secure aggregation and differential privacy are separate mechanisms.'],
    prerequisites: ['Stochastic gradient descent', 'Weighted averages and non-IID data'],
    readingNotes: ['Read the FedAvg algorithm and its local-epoch and client-fraction controls before the empirical comparisons.', 'Use the latest linked revision for pseudocode corrections while retaining the first-submission citation year. Compare accuracy and communication together.'],
    diagram: [node('Distribute model', 'Select clients and send the current model.'), node('Train locally', 'Each client updates the model using its own examples.'), node('Aggregate updates', 'Combine client models with the stated weighting rule.')],
    glossary: [term('Non-IID data', 'Client datasets are not independent samples from one identical distribution.'), term('Local epoch', 'One pass over a participating client dataset before communicating its update.')],
    exercise: exercise('Clients with 20 and 80 examples return a scalar parameter of 1 and 3. What does example-weighted averaging produce?', '0.2 × 1 + 0.8 × 3 = 2.6, not the unweighted 2. Explain that this arithmetic does not guarantee optimization convergence when clients have different distributions or participation patterns.'),
    related: [related('tensorflow', 'Separate the training execution system from the optimization algorithm.'), related('lora', 'Compare reducing trainable parameter volume with reducing client communication rounds.')],
  },
};
