import { ResearchPaperSchema } from './paperResearchSchema.js';

// Editorial synthesis, not copied abstracts. Dates refer to the cited edition.
// Helpers provide structure only; every lesson and comparison is paper-specific.
const verifiedOn = '2026-10-02';
const step = (label, detail) => ({ label, detail });
const term = (term, definition) => ({ term, definition });
const related = (id, reason) => ({ id, reason });
const code = (url, note) => ({ label: 'Official implementation', url, kind: 'Code', note });
const papers = [
  {
    id: 'raft', shortTitle: 'Raft', title: 'In Search of an Understandable Consensus Algorithm', year: 2014, venue: 'USENIX ATC', authors: ['Diego Ongaro', 'John Ousterhout'], category: 'Consensus',
    source: 'https://www.usenix.org/conference/atc14/technical-sessions/presentation/ongaro',
    problem: 'A replicated log needs one durable order of commands despite crashes, but a protocol that is difficult to understand is also difficult to implement correctly.',
    objective: 'Explain how election restrictions and log matching preserve committed entries across leader changes.',
    ideas: ['Separate leader election, log replication, and safety into explicit protocol rules.', 'A leader repairs follower logs; an up-to-date-log voting restriction prevents a stale candidate from discarding committed history.'],
    tradeoffs: ['A majority is needed for progress. A minority partition must not independently commit.', 'Timeouts affect availability and election stability, not the core safety argument; reads and membership changes need their own rules.'],
    prerequisites: ['Quorums', 'Replicated state machines'],
    readingNotes: ['Start with the condensed rules in Figure 2, then trace the safety argument rather than memorizing message names.', 'Read the current-term commit restriction carefully. Replication on several machines alone does not justify every commit decision.'],
    diagram: [step('Elect', 'Majority votes for an eligible candidate in a term.'), step('Replicate', 'Append entries and reconcile conflicting suffixes.'), step('Commit', 'Advance commit under the current-term rule, then apply in order.')],
    exercise: { prompt: 'Five replicas split into groups of three and two. Which side can elect a leader, and what happens when the old leader returns?', guidance: 'The group of three can form a majority. A higher term causes the old leader to step down; conflicting uncommitted entries can be overwritten, but committed history must survive.' },
    glossary: [term('Term', 'Monotonically increasing logical election epoch.'), term('Log matching', 'Matching index and term imply matching preceding entries.')],
    related: [related('paxos-simple', 'Compare safety reasoning with promises and accepted values in the existing model lab.'), related('zookeeper', 'Distinguish a consensus algorithm from a coordination service API.')],
  },
  {
    id: 'calvin', shortTitle: 'Calvin', title: 'Calvin: Fast Distributed Transactions for Partitioned Database Systems', year: 2012, venue: 'SIGMOD', authors: ['Alexander Thomson', 'Thaddeus Diamond', 'Shu-Chun Weng', 'Kun Ren', 'Philip Shao', 'Daniel J. Abadi'], category: 'Storage',
    source: 'https://cs.yale.edu/homes/thomson/publications/calvin-sigmod12.pdf',
    problem: 'Distributed commit holds contended locks across network coordination, making cross-partition transactions expensive.',
    objective: 'Contrast ordering transaction inputs before execution with coordinating commit after execution.',
    ideas: ['Replicate an ordered sequence of transaction inputs before deterministic execution.', 'Schedule conflicting operations consistently so participating partitions do not need a conventional distributed commit agreement at the end.'],
    tradeoffs: ['Read and write sets must be determined; dependent transactions require reconnaissance and possible restarts.', 'Ordering still requires coordination. Determinism does not remove network latency or make arbitrary application code safe to replay.'],
    prerequisites: ['Serializability', 'Two-phase locking', 'Partitioning'],
    readingNotes: ['Use the contention footprint discussion to explain why coordination placement matters.', 'Read the treatment of dependent transactions and disk access before generalizing the throughput results.'],
    diagram: [step('Sequence', 'Agree on ordered transaction inputs.'), step('Schedule', 'Acquire locks in a compatible deterministic order.'), step('Execute', 'Exchange required values and apply the predetermined transaction.')],
    exercise: { prompt: 'A transfer reads one account to discover a second account ID. Why is this harder than a transfer with both IDs supplied?', guidance: 'The access set depends on database state. A preliminary read may discover it, but execution must validate that discovery and retry if it is no longer valid.' },
    glossary: [term('Contention footprint', 'Time a transaction holds resources that conflicting transactions need.'), term('Deterministic execution', 'Equivalent ordered inputs produce equivalent transactional effects.')],
    related: [related('spanner', 'Compare input ordering with clock-assisted external consistency.'), related('foundationdb', 'Compare deterministic scheduling with optimistic conflict checking.')],
  },
  {
    id: 'foundationdb', shortTitle: 'FoundationDB', title: 'FoundationDB: A Distributed Unbundled Transactional Key Value Store', year: 2021, venue: 'SIGMOD', authors: ['Jingyu Zhou', 'Meng Xu', 'Alexander Shraer', 'Bala Namasivayam', 'Alex Miller', 'Evan Tschannen', 'Steve Atherton', 'Andrew J. Beamon', 'Rusty Sears', 'John Leach', 'Dave Rosenthal', 'Xin Dong', 'Will Wilson', 'Ben Collins', 'David Scherer', 'Alec Grieser', 'Young Liu', 'Alvin Moore', 'Bhaskar Muppana', 'Xiaoge Su', 'Vishesh Yadav'], category: 'Storage',
    source: 'https://www.foundationdb.org/files/fdb-paper.pdf',
    problem: 'Applications want scalable transactional storage without committing to a single database data model or query language.',
    objective: 'Separate transaction processing, durable logging, storage, and higher-level database layers.',
    ideas: ['Expose an ordered transactional key-value core while building richer models as layers.', 'Unbundle transaction management and storage roles; use deterministic simulation to explore faults in the implementation.'],
    tradeoffs: ['Optimistic conflicts cause retries; short transactions and explicit retry handling are part of the programming model.', 'A minimal core transfers indexing and query semantics to layers. Simulation coverage is strong engineering evidence, not a proof of all possible behavior.'],
    prerequisites: ['MVCC', 'Optimistic concurrency control'],
    readingNotes: ['Follow the read-version and commit paths separately before drawing the component diagram.', 'Treat the testing section as part of the architecture: controlled nondeterminism makes failure traces replayable.'],
    diagram: [step('Read version', 'Read a consistent snapshot through the client.'), step('Resolve and log', 'Check conflicts and durably record accepted mutations.'), step('Storage and layers', 'Storage catches up; layers interpret transactional keys.')],
    exercise: { prompt: 'Two transactions read the same balance and both subtract from it. What should a retry loop do after one conflicts?', guidance: 'Re-read the balance in a new transaction and recompute the change. Replaying only the old writes can violate the application invariant.' },
    glossary: [term('Layer', 'Software that implements a richer data model over the transactional key-value API.'), term('Conflict range', 'A key range used to detect conflicting concurrent operations.')],
    related: [related('calvin', 'Compare where each system pays for transaction coordination.'), related('percolator', 'Use the existing lab to contrast distributed transaction recovery.')],
    artifacts: [code('https://github.com/apple/foundationdb', 'Current project source, not a pinned reproduction of the 2021 evaluation.')],
  },
  {
    id: 'zookeeper', shortTitle: 'ZooKeeper', title: 'ZooKeeper: Wait-free Coordination for Internet-scale Systems', year: 2010, venue: 'USENIX ATC', authors: ['Patrick Hunt', 'Mahadev Konar', 'Flavio P. Junqueira', 'Benjamin Reed'], category: 'Consensus',
    source: 'https://www.usenix.org/conference/usenix-atc-10/zookeeper-wait-free-coordination-internet-scale-systems',
    problem: 'Distributed applications repeatedly implement fragile leader election, configuration, and group membership protocols.',
    objective: 'Build coordination recipes from ordered updates, sessions, and a small data-tree API.',
    ideas: ['Expose a hierarchical namespace with ephemeral and sequential nodes rather than one specialized lock API.', 'Use replicated ordered writes and local reads to support read-heavy coordination workloads.'],
    tradeoffs: ['A local read is not automatically the freshest global state; ordering guarantees and synchronization must be understood.', 'Session expiration is not the same as an instantaneous failure detector. External resources still need fencing against stale owners.'],
    prerequisites: ['Sessions', 'Replication', 'Ordering guarantees'],
    readingNotes: ['Read the guarantees before implementing a lock recipe; wait-free API terminology does not mean progress without a quorum.', 'Trace a client disconnect separately from session expiration and ephemeral-node deletion.'],
    diagram: [step('Client session', 'Maintain identity across transient connections.'), step('Ordered update', 'Replicate a mutation to the coordination tree.'), step('Watch and re-read', 'Use notifications to learn that state may have changed.')],
    exercise: { prompt: 'A paused lock holder resumes after its session expired. Can deleting its ephemeral node stop its old disk writes?', guidance: 'No. A fencing token checked by the protected resource is needed to reject operations from an obsolete holder.' },
    glossary: [term('Ephemeral node', 'A node whose lifetime is tied to its creating session.'), term('Watch', 'A notification mechanism that prompts a client to check changed state.')],
    related: [related('chubby', 'Compare coordination recipes with an advisory lock service.'), related('raft', 'Keep service semantics separate from replicated-log mechanics.')],
  },
  {
    id: 'ceph', shortTitle: 'Ceph', title: 'Ceph: A Scalable, High-Performance Distributed File System', year: 2006, venue: 'OSDI', authors: ['Sage A. Weil', 'Scott A. Brandt', 'Ethan L. Miller', 'Darrell D. E. Long', 'Carlos Maltzahn'], category: 'Storage',
    source: 'https://www.usenix.org/conference/osdi-06/ceph-scalable-high-performance-distributed-file-system',
    problem: 'A central file-to-storage allocation map and metadata bottlenecks limit distributed file-system growth.',
    objective: 'Explain how computed placement separates data access from metadata management.',
    ideas: ['CRUSH computes object placement from cluster structure instead of consulting a per-object allocation table.', 'Separate a dynamic metadata cluster from object storage devices that participate in replication and recovery.'],
    tradeoffs: ['Placement depends on a consistent cluster map and failure-domain model.', 'Rebalancing and recovery consume resources while foreground traffic continues; computed placement does not eliminate metadata coordination.'],
    prerequisites: ['Object storage', 'Replication', 'File-system metadata'],
    readingNotes: ['Distinguish pathname metadata from object placement; they solve different lookup problems.', 'Read the failure and recovery discussion alongside placement, not just the steady-state throughput evaluation.'],
    diagram: [step('Resolve metadata', 'Obtain file layout through the metadata service.'), step('Compute placement', 'Use CRUSH and a cluster map to locate objects.'), step('Access OSDs', 'Read and write data through object storage devices.')],
    exercise: { prompt: 'Why is hashing onto three disks insufficient if all three are in one rack?', guidance: 'Replica count does not capture correlated failures. Placement must encode rack boundaries, and repair must restore that separation.' },
    glossary: [term('OSD', 'Object storage device or daemon responsible for local objects and distributed storage duties.'), term('CRUSH', 'A placement algorithm that uses cluster topology and rules.')],
    related: [related('gfs', 'Contrast computed placement with master-managed chunk metadata.'), related('f4', 'Compare replica placement with coded storage across failure domains.')],
  },
  {
    id: 'haystack', shortTitle: 'Haystack', title: "Finding a Needle in Haystack: Facebook's Photo Storage", year: 2010, venue: 'OSDI', authors: ['Doug Beaver', 'Sanjeev Kumar', 'Harry C. Li', 'Jason Sobel', 'Peter Vajgel'], category: 'Storage',
    source: 'https://www.usenix.org/conference/osdi10/finding-needle-haystack-facebooks-photo-storage',
    problem: 'Serving a huge number of small photos can spend more disk operations on file-system metadata than on image data.',
    objective: 'Explain how packing objects and keeping compact indexes in memory reduces metadata I/O.',
    ideas: ['Store many photos as records in large files instead of using one file per photo.', 'Keep a compact in-memory mapping to object offsets and combine it with a cache and directory tier.'],
    tradeoffs: ['Append-oriented packing complicates space reclamation and deletion.', 'The design exploits photo workloads; arbitrary fine-grained mutable files need different semantics.'],
    prerequisites: ['Disk seeks', 'Caching', 'Append-only files'],
    readingNotes: ['Read the motivation around metadata disk operations before studying the storage layout.', 'Compare cache-hit and cache-miss paths, then examine what recovery must reconstruct.'],
    diagram: [step('Locate store', 'The directory identifies a volume and serving location.'), step('Resolve offset', 'A compact index locates a photo record.'), step('Read record', 'Fetch the photo from a large packed file.')],
    exercise: { prompt: 'Packing removes per-photo files. Does that also make deleted photos immediately reclaim their disk space?', guidance: 'No. Logical deletion and physical reclamation are different operations; compacting live records costs additional I/O.' },
    glossary: [term('Needle', 'A photo record stored within a Haystack store file.'), term('Metadata I/O', 'Storage operations used to locate data rather than transfer its payload.')],
    related: [related('f4', 'Follow the move from hot photo storage to warm coded BLOB storage.'), related('ceph', 'Compare workload-specific packing with a general distributed file system.')],
  },
  {
    id: 'f4', shortTitle: 'f4', title: "f4: Facebook's Warm BLOB Storage System", year: 2014, venue: 'OSDI', authors: ['Subramanian Muralidhar', 'Wyatt Lloyd', 'Sabyasachi Roy', 'Cory Hill', 'Ernest Lin', 'Weiwen Liu', 'Satadru Pan', 'Shiva Shankar', 'Viswanath Sivakumar', 'Linpeng Tang', 'Sanjeev Kumar'], category: 'Storage',
    source: 'https://www.usenix.org/conference/osdi14/technical-sessions/presentation/muralidhar',
    problem: 'Keeping multiple full replicas of rarely accessed BLOBs spends storage capacity on throughput that the workload does not need.',
    objective: 'Relate object temperature to redundancy, reconstruction cost, and failure-domain placement.',
    ideas: ['Separate hot and warm objects using their access behavior.', 'Use erasure coding and carefully placed redundancy to reduce storage overhead while retaining failure tolerance.'],
    tradeoffs: ['A missing fragment may require reads and decoding from multiple other fragments.', 'Warm-storage economics depend on access rates and recovery bandwidth, not just the coding ratio.'],
    prerequisites: ['Erasure coding', 'Failure domains'],
    readingNotes: ['Start with the observed change in BLOB access frequency over time.', 'Keep within-datacenter coding and cross-datacenter protection separate when calculating overhead.'],
    diagram: [step('Classify', 'Move suitable low-access BLOBs out of the hot tier.'), step('Encode', 'Create data and parity blocks across failure domains.'), step('Serve or rebuild', 'Read directly when healthy; reconstruct when fragments are lost.')],
    exercise: { prompt: 'Why can the lowest storage-overhead code be a poor choice during a rack failure?', guidance: 'Reconstruction can amplify disk and network traffic. Evaluate repair duration and foreground read latency along with bytes stored.' },
    glossary: [term('Warm BLOB', 'An object with lower access demand that still needs timely retrieval.'), term('Effective replication factor', 'Physical storage consumed relative to logical data size.')],
    related: [related('haystack', 'Read the hot-storage predecessor to understand the workload shift.'), related('colossus', 'Try the existing synthetic replication versus coding model.')],
  },
  {
    id: 'bw-tree', shortTitle: 'Bw-tree', title: 'The Bw-Tree: A B-tree for New Hardware Platforms', year: 2013, venue: 'ICDE', authors: ['Justin Levandoski', 'David Lomet', 'Sudipta Sengupta'], category: 'Storage',
    source: 'https://www.microsoft.com/en-us/research/publication/the-bw-tree-a-b-tree-for-new-hardware/',
    problem: 'Traditional index latches and in-place updates can limit concurrency and cache efficiency on multicore machines.',
    objective: 'Trace a latch-free index update through indirection, delta records, and consolidation.',
    ideas: ['Use a mapping table to separate logical page identity from physical location.', 'Install delta records with atomic pointer updates and consolidate chains into new base pages.'],
    tradeoffs: ['Long delta chains make reads more expensive until consolidation occurs.', 'Memory reclamation and structural changes remain subtle even without latches; latch-free does not mean no synchronization.'],
    prerequisites: ['B-tree indexes', 'Compare-and-swap', 'Memory reclamation'],
    readingNotes: ['Draw the mapping table before tracing an insert, since logical and physical addresses differ.', 'Study the concurrency and reclamation rules rather than assuming pointer swaps alone make deletion safe.'],
    diagram: [step('Logical page', 'Resolve a stable page ID through the mapping table.'), step('Delta chain', 'Read a base page plus newer changes.'), step('Consolidate', 'Replace a chain with a fresh compact representation.')],
    exercise: { prompt: 'Two writers build deltas from the same old pointer. What must the writer that loses compare-and-swap do?', guidance: 'Observe the new state and retry safely. It cannot assume its unpublished delta became part of the index.' },
    glossary: [term('Delta record', 'A change layered over an existing page representation.'), term('Latch-free', 'Progress without protecting each index operation with a conventional latch.')],
    related: [related('bigtable', 'Compare delta consolidation with immutable-table compaction.'), related('myrocks', 'Contrast an index concurrency design with an LSM storage engine.')],
  },
  {
    id: 'kafka', shortTitle: 'Kafka', title: 'Kafka: a Distributed Messaging System for Log Processing', year: 2011, venue: 'NetDB', authors: ['Jay Kreps', 'Neha Narkhede', 'Jun Rao'], category: 'Data Processing',
    source: 'https://www.microsoft.com/en-us/research/wp-content/uploads/2017/09/Kafka.pdf',
    problem: 'Log pipelines need high-throughput ingestion that serves both offline analytics and low-latency online consumers.',
    objective: 'Explain partitioned logs, pull consumption, batching, and replay in the original Kafka design.',
    ideas: ['Append messages in partitions and batch work to exploit sequential I/O.', 'Let consumers pull at their own pace and track their position independently of retained data.'],
    tradeoffs: ['Order is scoped to a partition, not the entire topic.', 'This 2011 paper is not a specification of modern Kafka transactions, replication, or exactly-once processing.'],
    prerequisites: ['Logs', 'Consumer offsets', 'Batching'],
    readingNotes: ['Read Section 3 for the log and consumption model, then examine the benchmark workload in Section 5.', 'Separate the original implementation and future-work discussion from features in current Kafka releases.'],
    diagram: [step('Batch append', 'Producers write records to partition logs.'), step('Retain', 'Stored records can serve multiple independent readers.'), step('Pull and advance', 'Each consumer fetches from its own position.')],
    exercise: { prompt: 'A consumer writes an external database row, then crashes before saving its offset. What can happen on restart?', guidance: 'The record can be replayed and its side effect duplicated. An idempotent write or coordinated offset and output transaction is needed beyond basic log replay.' },
    glossary: [term('Offset', 'A position within one partition log.'), term('Pull consumption', 'The consumer requests data when ready rather than accepting unbounded pushed work.')],
    related: [related('dataflow', 'Follow retained events into event-time computation.'), related('photon-pubsub', 'Explore duplicate delivery and deduplication in the model lab.')],
  },
  {
    id: 'rdd', shortTitle: 'Spark / RDDs', title: 'Resilient Distributed Datasets: A Fault-Tolerant Abstraction for In-Memory Cluster Computing', year: 2012, venue: 'NSDI', authors: ['Matei Zaharia', 'Mosharaf Chowdhury', 'Tathagata Das', 'Ankur Dave', 'Justin Ma', 'Murphy McCauley', 'Michael J. Franklin', 'Scott Shenker', 'Ion Stoica'], category: 'Data Processing',
    source: 'https://www.usenix.org/conference/nsdi12/technical-sessions/presentation/zaharia',
    problem: 'Iterative jobs repeatedly reload intermediate data while fine-grained distributed shared memory is expensive to recover.',
    objective: 'Use lineage and coarse-grained transformations to reason about recomputation after partition loss.',
    ideas: ['Represent immutable partitioned data using deterministic transformations and lineage.', 'Cache useful intermediate data while reconstructing lost partitions from their dependencies.'],
    tradeoffs: ['Lineage works well for bulk transformations, not arbitrary shared mutable state.', 'Wide dependencies and long lineage can make recovery costly; caching competes with other uses of memory.'],
    prerequisites: ['MapReduce', 'DAGs', 'Partitioning'],
    readingNotes: ['Compare narrow and wide dependencies before tracing a failed worker.', 'Read the iterative examples as motivation, then check the evaluation assumptions about caching and working-set size.'],
    diagram: [step('Transform', 'Build a lineage graph from immutable inputs.'), step('Persist', 'Keep selected partitions for reuse.'), step('Recompute', 'Recover lost partitions from available ancestors.')],
    exercise: { prompt: 'A cached map output is lost versus a shuffle output is lost. Why can the second require more upstream work?', guidance: 'A narrow dependency maps to limited parent partitions. A wide dependency can require contributions from many parents and additional shuffle traffic.' },
    glossary: [term('Lineage', 'The transformation history needed to reconstruct a dataset.'), term('Wide dependency', 'A dependency in which a child partition may need data from many parent partitions.')],
    related: [related('mapreduce', 'Contrast stage materialization with reusable in-memory datasets.'), related('dryad', 'Compare the data abstraction with a general execution graph.')],
  },
  {
    id: 'dryad', shortTitle: 'Dryad', title: 'Dryad: Distributed Data-parallel Programs from Sequential Building Blocks', year: 2007, venue: 'EuroSys', authors: ['Michael Isard', 'Mihai Budiu', 'Yuan Yu', 'Andrew Birrell', 'Dennis Fetterly'], category: 'Data Processing',
    source: 'https://www.microsoft.com/en-us/research/publication/dryad-distributed-data-parallel-programs-from-sequential-building-blocks/',
    problem: 'A fixed map-and-reduce structure does not naturally express every distributed data-processing job.',
    objective: 'Map sequential operators and communication channels onto a distributed execution DAG.',
    ideas: ['Compose sequential vertices into a graph whose edges carry data through files, pipes, or shared memory.', 'Let the execution engine place work, handle failures, and adapt execution to available resources.'],
    tradeoffs: ['Channel choices affect materialization, pipelining, and recovery costs.', 'An expressive graph still needs a suitable partitioning plan; data skew does not disappear behind the abstraction.'],
    prerequisites: ['Directed acyclic graphs', 'Task scheduling'],
    readingNotes: ['Trace the distinction between the logical graph and its runtime deployment.', 'Compare channel types and ask which intermediate results survive a process failure.'],
    diagram: [step('Compose vertices', 'Write sequential operators with input and output channels.'), step('Place graph', 'Schedule vertices near data when possible.'), step('Execute and recover', 'Move data and rerun affected work after failures.')],
    exercise: { prompt: 'Replace a durable intermediate file with a TCP pipe. What changes when the downstream task fails?', guidance: 'A pipe may require replay or re-execution of upstream work, whereas a completed durable file can be reread. Lower materialization cost can mean higher recovery cost.' },
    glossary: [term('Vertex', 'A sequential program instance within a distributed execution graph.'), term('Channel', 'A mechanism that transports records between vertices.')],
    related: [related('mapreduce', 'Identify which graph shapes exceed a single map-shuffle-reduce stage.'), related('rdd', 'Compare execution graphs with recoverable dataset lineage.')],
  },
  {
    id: 'dataflow', shortTitle: 'Dataflow model', title: 'The Dataflow Model: A Practical Approach to Balancing Correctness, Latency, and Cost in Massive-Scale, Unbounded, Out-of-Order Data Processing', year: 2015, venue: 'PVLDB', authors: ['Tyler Akidau', 'Robert Bradshaw', 'Craig Chambers', 'Slava Chernyak', 'Rafael J. Fernández-Moctezuma', 'Reuven Lax', 'Sam McVeety', 'Daniel Mills', 'Frances Perry', 'Eric Schmidt', 'Sam Whittle'], category: 'Data Processing',
    source: 'https://research.google/pubs/the-dataflow-model-a-practical-approach-to-balancing-correctness-latency-and-cost-in-massive-scale-unbounded-out-of-order-data-processing/',
    problem: 'Unbounded data can arrive late or out of order, so waiting for a permanently complete input is not a practical streaming model.',
    objective: 'Separate what is computed, where event-time windows fall, when results emit, and how revisions accumulate.',
    ideas: ['Use event-time windows independently from processing-time triggers.', 'Make latency, correctness, and resource tradeoffs explicit through watermark and accumulation semantics.'],
    tradeoffs: ['A watermark estimates completeness; it is not a universal promise that no late event can arrive.', 'Retaining state for late corrections costs memory and storage; early results may need revisions.'],
    prerequisites: ['Event time versus processing time', 'Windowed aggregation'],
    readingNotes: ['Draw one timeline with two clocks before studying triggers.', 'Follow the same late event through discarding, accumulating, and retracting result strategies instead of treating outputs as interchangeable.'],
    diagram: [step('Assign window', 'Group events by the time the event occurred.'), step('Trigger pane', 'Emit a result when the configured condition fires.'), step('Revise', 'Handle late data under the chosen accumulation policy.')],
    exercise: { prompt: 'An early pane reports 10 and a later accumulated pane reports 13. Should a downstream consumer sum them?', guidance: 'No, not if they represent revisions of the same window. Use replacement or explicit retractions; summing would report 23.' },
    glossary: [term('Watermark', 'An estimate of progress through event time.'), term('Pane', 'An emitted result for a window at a particular trigger firing.')],
    related: [related('millwheel', 'Try the watermark and late-record model lab.'), related('kafka', 'Separate durable ingestion from the semantics of computation.')],
  },
  {
    id: 'mesa', shortTitle: 'Mesa', title: 'Mesa: Geo-Replicated, Near Real-Time, Scalable Data Warehousing', year: 2014, venue: 'VLDB', authors: ['Ashish Gupta', 'Fan Yang', 'Jason Govig', 'Adam Kirsch', 'Kelvin Chan', 'Kevin Lai', 'Shuo Wu', 'Sandeep Dhoot', 'Abhilash Kumar', 'Ankur Agiwal', 'Sanjay Bhansali', 'Mingsheng Hong', 'Jamie Cameron', 'Masood Siddiqi', 'David Jones', 'Jeff Shute', 'Andrey Gubarev', 'Shivakumar Venkataraman', 'Divyakant Agrawal'], category: 'Data Processing',
    source: 'https://research.google/pubs/mesa-geo-replicated-near-real-time-scalable-data-warehousing/',
    problem: 'Advertising measurements need fresh aggregates and repeatable answers even when a datacenter fails.',
    objective: 'Explain how versioned updates and replicated serving support consistent analytical snapshots.',
    ideas: ['Maintain versioned aggregate data that can support repeatable queries.', 'Separate update processing and serving while replicating data across geographic sites.'],
    tradeoffs: ['Serving a consistent version can constrain freshness when replicas lag.', 'Pre-aggregation and maintenance are workload-specific; this is not an unrestricted OLTP design.'],
    prerequisites: ['Aggregation', 'Versioned snapshots', 'Replication'],
    readingNotes: ['Identify the query consistency contract before studying how data is replicated.', 'Trace the ingestion-to-query path and ask where a version becomes available to readers.'],
    diagram: [step('Ingest updates', 'Accept changes to analytical measurements.'), step('Version aggregates', 'Build and maintain queryable data versions.'), step('Serve snapshot', 'Return repeatable answers from an available consistent version.')],
    exercise: { prompt: 'Two dashboards use different committed versions. Can both be individually consistent while disagreeing?', guidance: 'Yes. Repeatability within a version does not imply that independently chosen versions represent the same point in the update stream.' },
    glossary: [term('Pre-aggregation', 'Combining records ahead of queries to reduce serving work.'), term('Versioned query', 'A query evaluated against a specific logical snapshot.')],
    related: [related('dremel', 'Compare analytical query execution with the maintenance of serving data.'), related('napa', 'Read a later Google warehousing design alongside Mesa.')],
  },
  {
    id: 'dapper', shortTitle: 'Dapper', title: 'Dapper, a Large-Scale Distributed Systems Tracing Infrastructure', year: 2010, venue: 'Google technical report', sourceType: 'Technical report', authors: ['Benjamin H. Sigelman', 'Luiz André Barroso', 'Mike Burrows', 'Pat Stephenson', 'Manoj Plakal', 'Donald Beaver', 'Saul Jaspan', 'Chandan Shanbhag'], category: 'Observability',
    source: 'https://research.google/pubs/dapper-a-large-scale-distributed-systems-tracing-infrastructure/',
    problem: 'A slow request crosses teams, processes, and machines, leaving no single local log that explains its path.',
    objective: 'Reconstruct a request tree while reasoning about instrumentation coverage and sampling bias.',
    ideas: ['Propagate trace context through common libraries to connect spans across service boundaries.', 'Use sampling and low-overhead instrumentation to make pervasive tracing operationally viable.'],
    tradeoffs: ['Sampling can miss rare failures; absence from a trace sample is not absence in production.', 'Missing context propagation breaks causal links, and cross-machine timing needs care.'],
    prerequisites: ['RPCs', 'Latency distributions', 'Sampling'],
    readingNotes: ['Start with the deployment goals of low overhead and application transparency.', 'Distinguish end-to-end critical-path latency from the sum of all child spans, which may overlap.'],
    diagram: [step('Propagate context', 'Carry trace and parent-span identity across RPCs.'), step('Collect spans', 'Record sampled events with service timing information.'), step('Reconstruct', 'Join records into a request-level dependency view.')],
    exercise: { prompt: 'Two child calls each last 40 ms and run in parallel. Is the parent necessarily at least 80 ms long?', guidance: 'No. Their elapsed times overlap. Use the critical path and account for parent work, queueing, and incomplete instrumentation.' },
    glossary: [term('Span', 'A timed operation within a distributed trace.'), term('Trace context', 'Identifiers used to relate operations across process boundaries.')],
    related: [related('tail-at-scale', 'Use traces to investigate the sources of tail latency.'), related('monarch', 'Compare individual request traces with aggregated time-series monitoring.')],
  },
  {
    id: 'tail-at-scale', shortTitle: 'The Tail at Scale', title: 'The Tail at Scale', year: 2013, venue: 'Communications of the ACM', sourceType: 'Research article', authors: ['Jeffrey Dean', 'Luiz André Barroso'], category: 'Infrastructure',
    source: 'https://research.google/pubs/the-tail-at-scale/',
    problem: 'Small probabilities of slow subrequests become common user-visible delays when requests fan out across many servers.',
    objective: 'Reason about fan-out amplification and the load cost of redundant requests.',
    ideas: ['Treat latency variability as a system design problem rather than relying on average service time.', 'Use techniques such as delayed hedged requests and coordinated redundant work to mitigate stragglers.'],
    tradeoffs: ['Redundancy can worsen overload unless delays, cancellation, and admission are controlled.', 'Subrequest delays may be correlated; independence-based calculations are illustrative rather than universal.'],
    prerequisites: ['Percentiles', 'Fan-out', 'Queueing'],
    readingNotes: ['Read the sources of variability before choosing a mitigation.', 'Distinguish hedged requests from tied requests and ask what happens to the losing copy.'],
    diagram: [step('Fan out', 'One user request depends on many subrequests.'), step('Observe tail', 'A straggler can dominate completion time.'), step('Mitigate carefully', 'Delay redundant work and cancel unnecessary copies.')],
    exercise: { prompt: 'In a synthetic independent model, each of 100 subrequests is slow with probability 0.01. What is the chance at least one is slow?', guidance: 'Compute 1 - 0.99^100, about 63.4%. This illustrates amplification, not a measured result from a production service.' },
    glossary: [term('Hedged request', 'A delayed duplicate sent when the initial request has not finished.'), term('Tail latency', 'Latency in the high-percentile portion of a distribution.')],
    related: [related('dapper', 'Connect request-level traces to straggler investigation.'), related('sre-workbook', 'Translate user-facing latency into an SLO and error budget.')],
  },
  {
    id: 'hnsw', shortTitle: 'HNSW', title: 'Efficient and robust approximate nearest neighbor search using Hierarchical Navigable Small World graphs', year: 2016, yearBasis: 'First arXiv submission', venue: 'arXiv:1603.09320', authors: ['Yu. A. Malkov', 'D. A. Yashunin'], category: 'Search',
    source: 'https://arxiv.org/abs/1603.09320',
    problem: 'Exact distance comparisons become expensive as the number of high-dimensional vectors grows.',
    objective: 'Explain hierarchical graph navigation and the recall, memory, and search-work tradeoff.',
    ideas: ['Build nested proximity graphs with randomly assigned maximum layers.', 'Navigate coarse upper layers before exploring a richer neighborhood near the query at the bottom layer.'],
    tradeoffs: ['Approximate search can miss true nearest neighbors; recall must be measured against exact results.', 'More graph edges and broader search improve some workloads at the cost of memory, construction time, and query work.'],
    prerequisites: ['Distance metrics', 'Nearest neighbors', 'Graphs'],
    readingNotes: ['Trace insertion and query separately, since build-time choices shape later search quality.', 'Check datasets, distance functions, and recall targets before comparing latency curves.'],
    diagram: [step('Coarse routing', 'Navigate sparse upper graph layers.'), step('Descend', 'Use the current neighborhood to enter denser layers.'), step('Explore candidates', 'Search a bounded candidate set at the bottom layer.')],
    exercise: { prompt: 'Why is comparing two indexes at different recall targets misleading?', guidance: 'One may be faster simply because it returns worse neighbors. Fix recall and report memory, build cost, and latency under the same dataset and distance function.' },
    glossary: [term('Recall@k', 'Fraction of exact top-k neighbors recovered by the approximate result.'), term('Proximity graph', 'A graph whose edges connect nearby items under a distance function.')],
    related: [related('faiss', 'Compare graph navigation with GPU search and compressed vectors.'), related('rag', 'Study how retrieval quality can limit downstream generation.')],
    artifacts: [code('https://github.com/nmslib/hnswlib', 'Author-associated implementation. Current code is not a pinned paper benchmark.')],
  },
  {
    id: 'faiss', shortTitle: 'Faiss / GPU search', title: 'Billion-scale similarity search with GPUs', year: 2017, yearBasis: 'First arXiv submission', venue: 'arXiv:1702.08734', authors: ['Jeff Johnson', 'Matthijs Douze', 'Hervé Jégou'], category: 'Search',
    source: 'https://arxiv.org/abs/1702.08734',
    problem: 'Large vector searches need efficient distance evaluation and top-k selection that actually exploit GPU hardware.',
    objective: 'Compare exact, approximate, and compressed-domain search under memory and recall constraints.',
    ideas: ['Design k-selection to exploit GPU parallelism and the memory hierarchy.', 'Combine optimized search with product quantization to make large vector collections practical.'],
    tradeoffs: ['Compression and pruning change recall, while exact brute-force search remains expensive at scale.', 'GPU transfer costs, batching, and available memory affect whether a workload benefits.'],
    prerequisites: ['Vector distances', 'GPU memory hierarchy', 'Quantization'],
    readingNotes: ['Separate the k-selection contribution from the choice of index.', 'Compare the paper-era implementation and benchmark hardware with the current Faiss repository before reproducing results.'],
    diagram: [step('Represent vectors', 'Choose full vectors or compressed codes.'), step('Compute candidates', 'Evaluate distances in GPU-friendly batches.'), step('Select top-k', 'Retain the nearest candidate results efficiently.')],
    exercise: { prompt: 'A compressed index fits in GPU memory but loses recall. Which measurements belong beside queries per second?', guidance: 'Report recall@k, index memory, build time, batch size, and end-to-end latency including transfers. Throughput alone hides quality and deployment costs.' },
    glossary: [term('Product quantization', 'Vector compression using separately quantized subspaces.'), term('k-selection', 'Selecting the k smallest or largest values from a candidate set.')],
    related: [related('hnsw', 'Compare a graph-based index with quantized and GPU-oriented search.'), related('rag', 'Connect dense-vector retrieval to a language-generation pipeline.')],
    artifacts: [code('https://github.com/facebookresearch/faiss', 'Official evolving search library. Select a revision and benchmark configuration before reproduction.')],
  },
  {
    id: 'attention', shortTitle: 'Transformer', title: 'Attention Is All You Need', year: 2017, yearBasis: 'First arXiv submission', venue: 'arXiv:1706.03762', authors: ['Ashish Vaswani', 'Noam Shazeer', 'Niki Parmar', 'Jakob Uszkoreit', 'Llion Jones', 'Aidan N. Gomez', 'Lukasz Kaiser', 'Illia Polosukhin'], category: 'Machine Learning',
    source: 'https://arxiv.org/abs/1706.03762',
    problem: 'Recurrent sequence models constrain parallel training and the paths through which distant tokens interact.',
    objective: 'Trace scaled dot-product attention, multiple heads, positional information, and decoder masking.',
    ideas: ['Use attention to mix information across tokens without a recurrent state transition.', 'Combine multi-head attention with position-wise feed-forward layers and positional information in an encoder-decoder architecture.'],
    tradeoffs: ['Dense attention involves a quadratic number of token pairs.', 'Parallel training does not imply parallel autoregressive generation; the original translation model is not identical to a modern decoder-only LLM.'],
    prerequisites: ['Matrix multiplication', 'Softmax', 'Encoder-decoder models'],
    readingNotes: ['Track tensor shapes through Q, K, and V before following the full architecture.', 'Read the masking and positional-encoding sections; neither token order nor causal visibility appears automatically.'],
    diagram: [step('Project tokens', 'Construct query, key, and value representations.'), step('Attend', 'Normalize scaled query-key scores under the visibility mask.'), step('Mix and transform', 'Combine values across heads and apply feed-forward layers.')],
    exercise: { prompt: 'In causal attention for four tokens, which keys can the third token use?', guidance: 'It can use positions one through three, not position four. The mask prevents future-token information from leaking into the prediction.' },
    glossary: [term('Attention head', 'One learned query-key-value projection and mixing operation.'), term('Causal mask', 'A restriction that hides later positions from an autoregressive prediction.')],
    related: [related('bert', 'Compare bidirectional representation learning with causal decoding.'), related('flashattention', 'Study an exact attention implementation that reduces memory traffic.')],
  },
  {
    id: 'bert', shortTitle: 'BERT', title: 'BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding', year: 2018, yearBasis: 'First arXiv submission', venue: 'arXiv:1810.04805', authors: ['Jacob Devlin', 'Ming-Wei Chang', 'Kenton Lee', 'Kristina Toutanova'], category: 'Machine Learning',
    source: 'https://arxiv.org/abs/1810.04805',
    problem: 'Language understanding benefits from both left and right context, but a standard left-to-right objective cannot directly train such representations.',
    objective: 'Explain masked-language pretraining and task-specific adaptation of a bidirectional encoder.',
    ideas: ['Predict selected masked tokens while conditioning on context on both sides.', 'Pretrain general representations and fine-tune them with small task-specific output heads; the original recipe also uses next-sentence prediction.'],
    tradeoffs: ['Masked pretraining differs from the inputs seen at fine-tuning time.', 'A bidirectional encoder is not directly an autoregressive generator, and downstream quality depends on adaptation and data.'],
    prerequisites: ['Transformer attention', 'Pretraining and fine-tuning'],
    readingNotes: ['Read the input representation and pretraining objectives together.', 'Use the ablations to distinguish evidence for bidirectionality from assumptions about later BERT variants.'],
    diagram: [step('Corrupt selected tokens', 'Construct masked-language training examples.'), step('Encode both directions', 'Let token representations use left and right context.'), step('Adapt task head', 'Fine-tune for classification, spans, or other understanding tasks.')],
    exercise: { prompt: 'Why would predicting each visible token from unrestricted bidirectional attention be a trivial training objective?', guidance: 'The input would reveal the target token. Masking or corruption prevents the simplest identity shortcut for selected targets.' },
    glossary: [term('Masked language model', 'An objective predicting selected hidden or corrupted tokens.'), term('Fine-tuning', 'Adapting pretrained parameters to a downstream objective.')],
    related: [related('attention', 'Review the encoder building blocks first.'), related('lora', 'Compare updating all parameters with low-rank adaptation.')],
    artifacts: [code('https://github.com/google-research/bert', 'Original TensorFlow implementation and checkpoint documentation; historical dependencies may need isolation.')],
  },
  {
    id: 'rag', shortTitle: 'RAG', title: 'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks', year: 2020, yearBasis: 'First arXiv submission', venue: 'arXiv:2005.11401', authors: ['Patrick Lewis', 'Ethan Perez', 'Aleksandra Piktus', 'Fabio Petroni', 'Vladimir Karpukhin', 'Naman Goyal', 'Heinrich Küttler', 'Mike Lewis', 'Wen-tau Yih', 'Tim Rocktäschel', 'Sebastian Riedel', 'Douwe Kiela'], category: 'Machine Learning',
    source: 'https://arxiv.org/abs/2005.11401',
    problem: 'A generator stores knowledge implicitly in parameters, making factual updates and access to supporting information difficult.',
    objective: 'Distinguish RAG-Sequence and RAG-Token and identify failure boundaries between retrieval and generation.',
    ideas: ['Combine a pretrained sequence-to-sequence model with a dense index of external passages.', 'Marginalize over retrieved documents at sequence or token granularity rather than treating one passage as certain.'],
    tradeoffs: ['Missing or misleading retrieved evidence limits what the generator can reliably answer.', 'Retrieval adds index maintenance and serving work; the paper does not establish a guarantee against hallucination.'],
    prerequisites: ['Dense retrieval', 'Sequence-to-sequence models'],
    readingNotes: ['Read the two probabilistic formulations before equating the paper with a modern prompt-and-retrieve application.', 'Separate retrieval evaluation from answer quality so failures can be attributed to the right stage.'],
    diagram: [step('Retrieve passages', 'Map a query to candidate external evidence.'), step('Condition generation', 'Use each retrieved passage with the input sequence.'), step('Marginalize', 'Combine document-conditioned probabilities under the chosen formulation.')],
    exercise: { prompt: 'The answer is absent from all retrieved passages, but the output sounds plausible. Which measurements would expose the failure?', guidance: 'Measure retrieval recall, answer correctness, and evidence support separately. Fluent output is not proof of retrieval success or grounding.' },
    glossary: [term('Parametric memory', 'Knowledge encoded in learned model weights.'), term('Non-parametric memory', 'An external retrievable collection, such as indexed passages.')],
    related: [related('hnsw', 'Study one approach to approximate vector retrieval.'), related('faiss', 'Examine the hardware and compression side of dense search.')],
  },
  {
    id: 'lora', shortTitle: 'LoRA', title: 'LoRA: Low-Rank Adaptation of Large Language Models', year: 2021, yearBasis: 'First arXiv submission', venue: 'arXiv:2106.09685', authors: ['Edward J. Hu', 'Yelong Shen', 'Phillip Wallis', 'Zeyuan Allen-Zhu', 'Yuanzhi Li', 'Shean Wang', 'Lu Wang', 'Weizhu Chen'], category: 'Machine Learning',
    source: 'https://arxiv.org/abs/2106.09685',
    problem: 'Full fine-tuning requires storing gradients and optimizer state for a large model and often a separate full model per task.',
    objective: 'Calculate low-rank update parameter counts and explain what memory costs remain.',
    ideas: ['Freeze pretrained weights and learn low-rank factors for selected weight updates.', 'Merge a learned update into a base weight for deployment when the serving setup allows it.'],
    tradeoffs: ['Rank and target modules restrict the adaptation space and affect task quality.', 'Reducing trainable parameters does not remove the base model, activations, or all inference costs; multi-adapter serving requires additional choices.'],
    prerequisites: ['Matrix rank', 'Gradient-based fine-tuning'],
    readingNotes: ['Track the shapes of both factors and distinguish trainable weights from total resident weights.', 'Read the rank experiments as empirical observations rather than a proof that every task has a low-rank solution.'],
    diagram: [step('Freeze base', 'Keep the pretrained weight matrix fixed.'), step('Train factors', 'Learn a low-rank update through two smaller matrices.'), step('Apply update', 'Use the base plus update, optionally merged for serving.')],
    exercise: { prompt: 'For a synthetic 1024 by 1024 weight and rank 8, how many factor parameters replace a full trainable update?', guidance: 'Two factors require 1024*8 + 8*1024 = 16,384 parameters, versus 1,048,576 for a full matrix. This excludes biases and other model components.' },
    glossary: [term('Low-rank update', 'A weight change represented as the product of two smaller matrices.'), term('Frozen parameter', 'A model parameter excluded from optimization during adaptation.')],
    related: [related('bert', 'Compare parameter-efficient adaptation with the original full fine-tuning recipe.'), related('chinchilla', 'Separate adaptation efficiency from pretraining compute allocation.')],
    artifacts: [code('https://github.com/microsoft/LoRA', 'Official loralib implementation and experiment resources.')],
  },
  {
    id: 'chinchilla', shortTitle: 'Chinchilla', title: 'Training Compute-Optimal Large Language Models', year: 2022, yearBasis: 'First arXiv submission', venue: 'arXiv:2203.15556', authors: ['Jordan Hoffmann', 'Sebastian Borgeaud', 'Arthur Mensch', 'Elena Buchatskaya', 'Trevor Cai', 'Eliza Rutherford', 'Diego de Las Casas', 'Lisa Anne Hendricks', 'Johannes Welbl', 'Aidan Clark', 'Tom Hennigan', 'Eric Noland', 'Katie Millican', 'George van den Driessche', 'Bogdan Damoc', 'Aurelia Guy', 'Simon Osindero', 'Karen Simonyan', 'Erich Elsen', 'Jack W. Rae', 'Oriol Vinyals', 'Laurent Sifre'], category: 'Machine Learning',
    source: 'https://arxiv.org/abs/2203.15556',
    problem: 'A fixed pretraining compute budget can be spent on more parameters or more training tokens, and scaling only parameters can undertrain a model.',
    objective: 'Explain compute-budget tradeoffs without treating a fitted scaling relationship as a universal constant.',
    ideas: ['Fit loss behavior across model sizes and token budgets to estimate a compute-efficient allocation.', 'Test the predicted allocation with Chinchilla, a smaller model trained on more tokens than Gopher under a comparable training budget.'],
    tradeoffs: ['The result depends on model family, dataset, optimization, and the range used for fitting.', 'Training-compute optimality is a different objective from minimizing total lifetime cost including inference.'],
    prerequisites: ['Training loss', 'Scaling laws', 'Compute budgets'],
    readingNotes: ['Compare the different fitting approaches and their assumptions before extracting a rule of thumb.', 'Keep parameter counts, token counts, and total training compute distinct in notes and comparisons.'],
    diagram: [step('Choose budget', 'Fix the amount of pretraining computation.'), step('Allocate', 'Trade model size against number of training tokens.'), step('Validate', 'Check fitted predictions against trained models and downstream tasks.')],
    exercise: { prompt: 'If inference volume is enormous, must the training-compute-optimal model also minimize total cost?', guidance: 'No. A smaller model trained for longer may cost more to train but less to serve. The objective must include expected inference demand and quality constraints.' },
    glossary: [term('Compute-optimal', 'Best predicted quality under a specified computation budget and model assumptions.'), term('Scaling law', 'An empirical relationship between resources and a measured model outcome.')],
    related: [related('attention', 'Review the architecture being scaled.'), related('pagedattention', 'Contrast training allocation with serving-time memory efficiency.')],
  },
  {
    id: 'flashattention', shortTitle: 'FlashAttention', title: 'FlashAttention: Fast and Memory-Efficient Exact Attention with IO-Awareness', year: 2022, yearBasis: 'First arXiv submission', venue: 'arXiv:2205.14135', authors: ['Tri Dao', 'Daniel Y. Fu', 'Stefano Ermon', 'Atri Rudra', 'Christopher Ré'], category: 'Machine Learning',
    source: 'https://arxiv.org/abs/2205.14135',
    problem: 'Attention spends substantial time moving intermediate matrices between GPU memory levels, not just performing arithmetic.',
    objective: 'Explain how tiled exact attention avoids materializing the full attention matrix in high-bandwidth memory.',
    ideas: ['Tile the computation to reuse data in fast on-chip memory.', 'Maintain softmax statistics across tiles and recompute intermediates in the backward pass to reduce memory traffic.'],
    tradeoffs: ['Dense attention still requires quadratic arithmetic in sequence length; reduced I/O is not linear-time attention.', 'Wall-clock gains depend on hardware, shapes, precision, and kernel implementation. Exact describes the algorithm, not bit-identical floating-point ordering.'],
    prerequisites: ['Attention', 'Softmax', 'GPU memory hierarchy'],
    readingNotes: ['Follow the memory-access accounting alongside FLOP counts.', 'Distinguish the exact dense algorithm from the separate block-sparse extension.'],
    diagram: [step('Load tile', 'Bring blocks of queries, keys, and values into fast memory.'), step('Update statistics', 'Combine partial softmax results without a full stored score matrix.'), step('Write output', 'Persist the output and necessary compact state.')],
    exercise: { prompt: 'If an implementation never stores the N by N score matrix, does it necessarily perform only O(N) arithmetic?', guidance: 'No. It can still evaluate all token pairs while avoiding quadratic intermediate storage and reducing slow-memory traffic.' },
    glossary: [term('IO-aware', 'Designed around data transfers between memory levels.'), term('Tiling', 'Processing blocks of a larger computation to exploit locality.')],
    related: [related('attention', 'Read the mathematical operation before its optimized implementation.'), related('pagedattention', 'Compare attention-kernel I/O with serving-time KV-cache allocation.')],
    artifacts: [code('https://github.com/Dao-AILab/flash-attention', 'Official repository now includes later generations; pin a version for paper-specific experiments.')],
  },
  {
    id: 'pagedattention', shortTitle: 'vLLM / PagedAttention', title: 'Efficient Memory Management for Large Language Model Serving with PagedAttention', year: 2023, venue: 'SOSP', authors: ['Woosuk Kwon', 'Zhuohan Li', 'Siyuan Zhuang', 'Ying Sheng', 'Lianmin Zheng', 'Cody Hao Yu', 'Joseph E. Gonzalez', 'Hao Zhang', 'Ion Stoica'], category: 'Machine Learning',
    source: 'https://arxiv.org/abs/2309.06180',
    problem: 'Growing per-request KV caches cause fragmentation and duplicated memory, limiting the number of requests a serving system can batch.',
    objective: 'Trace logical KV-cache blocks to physical storage and distinguish allocation efficiency from model arithmetic.',
    ideas: ['Manage KV-cache memory in blocks inspired by virtual-memory paging.', 'Use flexible block sharing to avoid redundant cache storage across related sequences.'],
    tradeoffs: ['Block tables, allocation, and scheduling add implementation complexity.', 'Paging does not shrink model weights or guarantee a latency target under arbitrary load; current vLLM has evolved beyond the paper.'],
    prerequisites: ['Autoregressive decoding', 'KV caches', 'Virtual memory'],
    readingNotes: ['Read the fragmentation examples before the block-mapping mechanism.', 'Compare throughput only at comparable latency and workload settings, including sequence lengths and decoding strategy.'],
    diagram: [step('Logical sequence', 'Represent growing token history as logical blocks.'), step('Block table', 'Map sequence blocks to non-contiguous physical cache blocks.'), step('Batch decoding', 'Use available cache capacity to serve active sequences.')],
    exercise: { prompt: 'Two generated branches share a prompt. When does their shared cache need separate storage?', guidance: 'The unchanged prefix can remain shared. Writes to a shared partial block require copy-on-write handling, and divergent suffixes need their own blocks.' },
    glossary: [term('KV cache', 'Stored key and value tensors reused during autoregressive decoding.'), term('Internal fragmentation', 'Unused capacity inside an allocated block.')],
    related: [related('virtual-memory', 'Try the existing address-translation demo behind the paging analogy.'), related('flashattention', 'Separate cache allocation from memory-efficient attention computation.')],
    artifacts: [code('https://github.com/vllm-project/vllm', 'Official serving engine; current features and performance differ from the 2023 system.')],
  },
];

export const researchPapers = papers.map(paper => ResearchPaperSchema.parse({
  sourceType: 'Research paper', yearBasis: 'Publication', verifiedOn,
  ...paper,
  artifacts: [{ label: 'Original paper and source record', url: paper.source, kind: paper.source.endsWith('.pdf') || paper.source.includes('arxiv.org') ? 'Paper' : 'Publisher materials', note: 'Primary source for the citation and reading guide. Publisher pages may also provide the paper, slides, or talk.' }, ...(paper.artifacts || [])],
}));
export const researchById = Object.fromEntries(researchPapers.map(p => [p.id, p]));

export const learningPaths = [
  { id: 'coordination', title: 'From agreement to transactions', question: 'Where does a distributed system pay for coordination?', ids: ['paxos-simple', 'raft', 'zookeeper', 'spanner', 'calvin', 'foundationdb'] },
  { id: 'storage', title: 'Storage under real workloads', question: 'How do object size, access temperature, and failure domains change a design?', ids: ['gfs', 'ceph', 'haystack', 'f4', 'bw-tree', 'bigtable'] },
  { id: 'data', title: 'From batch to unbounded data', question: 'What can be replayed, and when is an answer complete?', ids: ['mapreduce', 'dryad', 'rdd', 'kafka', 'millwheel', 'dataflow', 'mesa'] },
  { id: 'retrieval', title: 'Search to grounded generation', question: 'Where can information be lost between a vector and an answer?', ids: ['idf-symbolic-sim', 'hnsw', 'faiss', 'attention', 'bert', 'rag'] },
  { id: 'llm-systems', title: 'The cost of a language model', question: 'Which bottleneck belongs to training, adaptation, kernels, or serving?', ids: ['attention', 'chinchilla', 'lora', 'flashattention', 'virtual-memory', 'pagedattention'] },
  { id: 'operations', title: 'Observe the long tail', question: 'Can a healthy average hide an unhealthy user experience?', ids: ['dapper', 'tail-at-scale', 'monarch', 'sre-workbook'] },
];
